(function(){
"use strict";
var CHANGE_STORAGE="clarity_v0_change_state",HISTORY="clarity_v0_history";
var OTHER=["clarity_v0_state","clarity_v0_confidence_state","clarity_v0_procrastination_state","clarity_v0_lost_state","clarity_v0_rumination_state","clarity_v0_limits_state","clarity_v0_failure_state","clarity_v0_motivation_state","clarity_v0_relationship_state"];
var active=false,stepIndex=0,data={};
var steps=["intro","domain","sentence","scale","bridge","future","preserve","priorities","top3","less","tenPercent","direction","test","reversible","learning","action","summary"];
var domains=["Travail / études","Relations","Famille","Santé / énergie","Temps / rythme de vie","Lieu de vie","Argent / sécurité","Habitudes / quotidien","Sens / direction générale","Plusieurs domaines à la fois"];
var priorities=["Liberté","Sécurité","Temps","Énergie","Relations","Sens","Apprentissage","Créativité","Stabilité","Autonomie","Plaisir","Calme","Évolution","Santé","Contribution"];
var directions=[
 {id:"modify",label:"Modifier",hint:"Changer quelque chose qui existe déjà."},
 {id:"add",label:"Ajouter",hint:"Faire entrer un nouvel élément dans ma vie."},
 {id:"explore",label:"Explorer",hint:"Tester une piste sans engagement définitif."},
 {id:"remove",label:"Retirer",hint:"Réduire ou arrêter quelque chose qui prend trop de place."},
 {id:"space",label:"Faire de la place",hint:"Créer du temps, de l’énergie ou de l’attention avant de décider davantage."}
];
function esc(s){return String(s||"").replace(/[&<>"']/g,function(m){return({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"})[m]});}
function nav(disabled){return '<div class="navrow"><button class="secondary" id="chgBack" '+(disabled?'disabled':'')+'>Retour</button><button class="cta" id="chgNext">Continuer</button></div>';}
function item(t,v){return '<div class="summary-item"><b>'+esc(t)+'</b><span>'+esc(v||"—")+'</span></div>';}
function fmtDate(iso){if(!iso)return "";return new Date(iso+"T12:00:00").toLocaleDateString("fr-FR",{day:"numeric",month:"long",year:"numeric"});}
function history(){try{return JSON.parse(localStorage.getItem(HISTORY)||"[]")}catch(e){return[]}}
function noOther(){return OTHER.every(function(k){return !localStorage.getItem(k)})}
function clearOthers(){OTHER.forEach(function(k){localStorage.removeItem(k)})}
function read(){try{var raw=localStorage.getItem(CHANGE_STORAGE);if(!raw)return false;var s=JSON.parse(raw);data=s.data||{};stepIndex=Number.isInteger(s.step)?s.step:0;if(stepIndex<0||stepIndex>=steps.length)stepIndex=0;return true}catch(e){return false}}
function save(){localStorage.setItem(CHANGE_STORAGE,JSON.stringify({data:data,step:stepIndex}));showResume();}
function clear(){localStorage.removeItem(CHANGE_STORAGE);data={};stepIndex=0;}
function showResume(){if(!noOther())return;var c=document.getElementById("resumeCard"),t=document.getElementById("resumeText");if(!c||!t)return;c.classList.remove("hidden");t.textContent=data.sentence?"Tu explorais un changement autour de : « "+data.sentence+" »":"Tu as un parcours Le Pont vers la suite en cours.";}
function sticky(){var t=document.querySelector(".topbar");if(t)document.documentElement.style.setProperty("--topbar-h",t.offsetHeight+"px");}
function start(fresh){if(fresh){clearOthers();clear()}else read();document.querySelectorAll(".screen").forEach(function(s){s.classList.remove("active")});document.getElementById("flow").classList.add("active");document.querySelector(".bottom").classList.add("hidden");document.getElementById("resetBtn").classList.remove("hidden");document.querySelectorAll(".tab").forEach(function(t){t.classList.remove("active")});active=true;render();}
function dirLabel(){var d=directions.find(function(x){return x.id===data.direction});return d?d.label:"—";}
function chosen(list,x){return (list||[]).indexOf(x)>=0;}
function toggle(list,x,max){list=list||[];var i=list.indexOf(x);if(i>=0)list.splice(i,1);else if(list.length<max)list.push(x);return list;}
function proposedAction(){return data.action||data.test||data.tenAction||"";}
function reversibilityInsight(){if(data.reversible==="Oui, facilement")return "Un changement réversible peut être traité comme une expérience plutôt que comme une décision définitive.";if(data.reversible==="En partie")return "Tu peux chercher la partie réversible du changement et tester seulement celle-ci.";if(data.reversible==="Non, difficilement")return "Si le changement est difficile à inverser, le test doit porter sur l’information à recueillir avant d’agir — pas sur le grand changement lui-même.";return "La réversibilité aide à choisir la bonne taille de test.";}
function render(){
 var step=steps[stepIndex],host=document.getElementById("flowContent"),flow=document.getElementById("flow");
 flow.classList.toggle("sticky-question",step!=="intro"&&step!=="summary");
 document.getElementById("progress").style.width=Math.round(stepIndex/(steps.length-1)*100)+"%";
 if(step==="intro")host.innerHTML='<div class="hero"><div class="eyebrow">Le Pont vers la suite</div><h2>Tu n’as pas besoin de tout changer pour vérifier qu’une autre direction te convient mieux.</h2><p>On va regarder ce que tu veux laisser derrière, ce que tu veux préserver et ce que tu veux voir davantage, puis construire un changement à +10 %.</p></div><div class="card soft-green"><b>Objectif</b><p>Passer d’un besoin vague de changement à une direction concrète et un test réversible autant que possible.</p></div>'+nav(true);
 if(step==="domain")host.innerHTML='<div class="hero"><div class="eyebrow">1 · Le domaine</div><h2>Dans quelle partie de ta vie sens-tu le plus besoin de changement&nbsp;?</h2></div><div class="choices">'+domains.map(function(x){return '<button class="choice '+(data.domain===x?'selected':'')+'" data-chg-domain="'+esc(x)+'">'+esc(x)+'</button>'}).join("")+'</div>'+nav(false);
 if(step==="sentence")host.innerHTML='<div class="hero"><div class="eyebrow">2 · Ce qui doit évoluer</div><h2>Complète : “Je sais que quelque chose doit changer parce que…”</h2></div><div class="field"><textarea id="chgSentence" placeholder="Ex. mes semaines ne ressemblent plus à ce que je veux vivre…">'+esc(data.sentence||"")+'</textarea></div>'+nav(false);
 if(step==="scale"){var n=Number(data.scale||0);host.innerHTML='<div class="hero"><div class="eyebrow">3 · L’intensité</div><h2>À quel point ce besoin de changement est-il présent aujourd’hui&nbsp;?</h2></div><div class="chips">'+[1,2,3,4,5].map(function(x){return '<button class="chip '+(n===x?'selected':'')+'" data-chg-scale="'+x+'">'+x+'</button>'}).join("")+'</div><p class="muted">1 = léger inconfort · 5 = je ne veux vraiment plus continuer comme ça.</p><div class="field"><label>Depuis quand ? <span class="muted">(facultatif)</span></label><input id="chgSince" type="text" placeholder="Ex. depuis environ six mois" value="'+esc(data.since||"")+'"></div>'+nav(false)}
 if(step==="bridge")host.innerHTML='<div class="hero"><div class="eyebrow">4 · Les quatre points du pont</div><h2>Avant de chercher une solution, précise ce que le changement doit respecter.</h2></div><div class="card coral"><div class="field"><label>Ce que je veux laisser derrière moi</label><textarea id="chgLeave" placeholder="Une situation, une contrainte, une habitude, un rythme…">'+esc(data.leave||"")+'</textarea></div></div><div class="card soft-green"><div class="field"><label>Ce que je veux préserver</label><textarea id="chgKeep" placeholder="Ce qui fonctionne déjà et que tu ne veux pas sacrifier…">'+esc(data.keep||"")+'</textarea></div></div><div class="card cream"><div class="field"><label>Ce dont je veux davantage</label><textarea id="chgMore" placeholder="Temps, sens, liberté, stabilité, lien, énergie…">'+esc(data.more||"")+'</textarea></div></div><div class="card"><div class="field"><label>Ce que j’ai envie d’explorer</label><textarea id="chgExplore" placeholder="Une piste, un environnement, une activité, une façon de vivre…">'+esc(data.explore||"")+'</textarea></div></div>'+nav(false);
 if(step==="future")host.innerHTML='<div class="hero"><div class="eyebrow">5 · Si rien ne change</div><h2>Si ta situation reste exactement la même pendant un an, qu’est-ce qui risque de te peser le plus&nbsp;?</h2></div><div class="field"><textarea id="chgFuture" placeholder="Ex. avoir l’impression d’avoir encore repoussé quelque chose d’important…">'+esc(data.futureCost||"")+'</textarea></div>'+nav(false);
 if(step==="preserve")host.innerHTML='<div class="hero"><div class="eyebrow">6 · Ce que tu refuses de perdre</div><h2>Quelles sont les 1 à 3 choses que le changement doit absolument préserver&nbsp;?</h2><p class="muted">Une bonne direction ne mérite pas forcément de sacrifier tout le reste.</p></div><div class="field"><textarea id="chgPreserve" placeholder="Ex. ma sécurité financière, du temps avec mes proches, ma santé…">'+esc(data.preserve||"")+'</textarea></div>'+nav(false);
 if(step==="priorities")host.innerHTML='<div class="hero"><div class="eyebrow">7 · Ce que tu veux davantage</div><h2>Choisis jusqu’à 5 éléments que tu voudrais voir davantage dans la suite.</h2><p class="muted">Tu en garderas ensuite 3 prioritaires.</p></div><div class="chips">'+priorities.map(function(x){return '<button class="chip '+(chosen(data.morePriorities,x)?'selected':'')+'" data-chg-priority="'+esc(x)+'">'+esc(x)+'</button>'}).join("")+'</div><p class="muted">'+((data.morePriorities||[]).length)+' / 5 sélectionnés</p>'+nav(false);
 if(step==="top3")host.innerHTML='<div class="hero"><div class="eyebrow">8 · Tes trois repères</div><h2>Parmi tes choix, lesquels sont vraiment prioritaires maintenant&nbsp;?</h2><p class="muted">Choisis au maximum 3 repères.</p></div><div class="chips">'+(data.morePriorities||[]).map(function(x){return '<button class="chip '+(chosen(data.top3,x)?'selected':'')+'" data-chg-top3="'+esc(x)+'">'+esc(x)+'</button>'}).join("")+'</div><p class="muted">'+((data.top3||[]).length)+' / 3 sélectionnés</p>'+nav(false);
 if(step==="less")host.innerHTML='<div class="hero"><div class="eyebrow">9 · Faire de la place</div><h2>De quoi voudrais-tu moins pour permettre à ces priorités de prendre plus de place&nbsp;?</h2></div><div class="field"><textarea id="chgLess" placeholder="Ex. moins de trajets, moins d’obligations sociales, moins de travail le soir…">'+esc(data.less||"")+'</textarea></div>'+nav(false);
 if(step==="tenPercent")host.innerHTML='<div class="hero"><div class="eyebrow">10 · Ta vie à +10 %</div><h2>Sans tout bouleverser, à quoi ressemblerait une version seulement 10 % plus proche de ce que tu veux&nbsp;?</h2><p class="muted">Si tu as envie de “tout changer”, commence ici : une différence visible mais limitée.</p></div><div class="field"><textarea id="chgTen" placeholder="Ex. une demi-journée par semaine consacrée à autre chose, un rendez-vous exploratoire, moins d’une obligation…">'+esc(data.tenPercent||"")+'</textarea></div>'+nav(false);
 if(step==="direction")host.innerHTML='<div class="hero"><div class="eyebrow">11 · La forme du changement</div><h2>Quelle direction décrit le mieux ton prochain mouvement&nbsp;?</h2></div><div class="choices">'+directions.map(function(x){return '<button class="choice '+(data.direction===x.id?'selected':'')+'" data-chg-direction="'+x.id+'"><b>'+esc(x.label)+'</b><span class="muted" style="display:block;font-size:13px;margin-top:4px;font-weight:500">'+esc(x.hint)+'</span></button>'}).join("")+'</div>'+nav(false);
 if(step==="test")host.innerHTML='<div class="hero"><div class="eyebrow">12 · Tester la direction</div><h2>Quel petit test pourrait te dire si cette direction mérite d’aller plus loin&nbsp;?</h2><p class="muted">Le test doit t’apprendre quelque chose, pas t’obliger à prendre tout de suite une décision définitive.</p></div><div class="field"><label>Mon test</label><input id="chgTest" type="text" placeholder="Ex. passer une journée dans ce nouvel environnement / parler à deux personnes / essayer ce rythme pendant une semaine" value="'+esc(data.test||"")+'"></div>'+nav(false);
 if(step==="reversible")host.innerHTML='<div class="hero"><div class="eyebrow">13 · Réversibilité</div><h2>Si ce test ne te convient pas, peux-tu facilement revenir en arrière&nbsp;?</h2></div><div class="choices">'+["Oui, facilement","En partie","Non, difficilement","Je ne sais pas encore"].map(function(x){return '<button class="choice '+(data.reversible===x?'selected':'')+'" data-chg-reversible="'+esc(x)+'">'+esc(x)+'</button>'}).join("")+'</div>'+(data.reversible?'<div class="insight">'+reversibilityInsight()+'</div>':'')+((data.reversible==="Non, difficilement")?'<div class="field"><label>Version plus réversible du test</label><input id="chgSaferTest" type="text" placeholder="Ex. recueillir des informations, simuler, tester temporairement avant de s’engager…" value="'+esc(data.saferTest||"")+'"></div>':'')+nav(false);
 if(step==="learning")host.innerHTML='<div class="hero"><div class="eyebrow">14 · Ce que tu veux apprendre</div><h2>À la fin du test, quelle question veux-tu pouvoir mieux répondre&nbsp;?</h2><p class="muted">C’est cette réponse — pas la réussite parfaite du test — qui donnera de la valeur à l’expérience.</p></div><div class="field"><textarea id="chgLearning" placeholder="Ex. Est-ce que ce rythme me donne réellement plus d’énergie ? Est-ce que ce métier m’intéresse une fois vu de près ?">'+esc(data.learning||"")+'</textarea></div>'+nav(false);
 if(step==="action"){var p=(data.reversible==="Non, difficilement"&&data.saferTest)?data.saferTest:data.test;host.innerHTML='<div class="hero"><div class="eyebrow">15 · Prochain pas</div><h2>Quel est le premier pas concret vers ce test&nbsp;?</h2></div><div class="card soft-green"><label>Mon prochain pas</label><input id="chgAction" type="text" value="'+esc(data.action||p||"")+'" placeholder="Mon premier pas concret"></div><div class="field"><label>Quand ?</label><input id="chgDate" type="date" value="'+esc(data.actionDate||"")+'"></div>'+nav(false)}
 if(step==="summary")host.innerHTML='<div class="hero"><div class="eyebrow">Ton Pont vers la suite</div><h2>Tu n’as pas besoin de connaître toute la destination pour tester une direction.</h2></div><div class="summary-grid">'+item("Domaine",data.domain)+item("Pourquoi ça doit changer",data.sentence)+item("À laisser derrière",data.leave)+item("À préserver",data.preserve||data.keep)+item("À retrouver davantage",(data.top3||[]).join(", "))+item("Moins de",data.less)+item("Version à +10 %",data.tenPercent)+item("Direction",dirLabel())+item("Test",data.test)+item("Réversibilité",data.reversible)+item("Ce que tu veux apprendre",data.learning)+'</div><div class="card soft-green"><div class="eyebrow">Prochain pas</div><h3>'+esc(data.action||"À définir")+'</h3><p>'+(data.actionDate?fmtDate(data.actionDate):"Sans date définie")+'</p></div><div class="insight">Le test n’est pas une promesse de tout changer. Il sert à vérifier si cette direction mérite davantage de place dans ta vie.</div><button class="cta" id="chgFinish">Enregistrer dans Mon parcours</button><div style="height:10px"></div><button class="secondary" id="chgEdit">Modifier une réponse</button>';
 bind(step);updateNext(step);sticky();save();requestAnimationFrame(function(){window.scrollTo(0,0)});
}
function capture(step){function v(id){var e=document.getElementById(id);return e?e.value.trim():""}if(step==="sentence")data.sentence=v("chgSentence");if(step==="scale")data.since=v("chgSince");if(step==="bridge"){data.leave=v("chgLeave");data.keep=v("chgKeep");data.more=v("chgMore");data.explore=v("chgExplore")}if(step==="future")data.futureCost=v("chgFuture");if(step==="preserve")data.preserve=v("chgPreserve");if(step==="less")data.less=v("chgLess");if(step==="tenPercent")data.tenPercent=v("chgTen");if(step==="test")data.test=v("chgTest");if(step==="reversible")data.saferTest=v("chgSaferTest");if(step==="learning")data.learning=v("chgLearning");if(step==="action"){data.action=v("chgAction");data.actionDate=v("chgDate")}}
function valid(step){if(step==="domain")return !!data.domain;if(step==="sentence")return !!data.sentence;if(step==="scale")return !!data.scale;if(step==="bridge")return !!data.leave&&!!data.keep&&!!data.more;if(step==="future")return !!data.futureCost;if(step==="preserve")return !!data.preserve;if(step==="priorities")return !!(data.morePriorities&&data.morePriorities.length);if(step==="top3")return !!(data.top3&&data.top3.length);if(step==="less")return !!data.less;if(step==="tenPercent")return !!data.tenPercent;if(step==="direction")return !!data.direction;if(step==="test")return !!data.test;if(step==="reversible")return !!data.reversible&&(data.reversible!=="Non, difficilement"||!!data.saferTest);if(step==="learning")return !!data.learning;if(step==="action")return !!data.action;return true}
function updateNext(step){var n=document.getElementById("chgNext");if(!n)return;capture(step);n.disabled=!valid(step)}
function only(sel,b){document.querySelectorAll(sel).forEach(function(x){x.classList.remove("selected")});b.classList.add("selected")}
function bind(step){
 var back=document.getElementById("chgBack"),next=document.getElementById("chgNext");
 if(back)back.onclick=function(){capture(step);if(stepIndex>0){stepIndex--;render()}};
 if(next)next.onclick=function(){capture(step);if(valid(step)){stepIndex++;render()}};
 document.querySelectorAll("[data-chg-domain]").forEach(function(b){b.onclick=function(){data.domain=b.dataset.chgDomain;only("[data-chg-domain]",b);save();updateNext(step)}});
 document.querySelectorAll("[data-chg-scale]").forEach(function(b){b.onclick=function(){data.scale=Number(b.dataset.chgScale);render()}});
 document.querySelectorAll("[data-chg-priority]").forEach(function(b){b.onclick=function(){data.morePriorities=toggle(data.morePriorities,b.dataset.chgPriority,5);data.top3=(data.top3||[]).filter(function(x){return chosen(data.morePriorities,x)});render()}});
 document.querySelectorAll("[data-chg-top3]").forEach(function(b){b.onclick=function(){data.top3=toggle(data.top3,b.dataset.chgTop3,3);render()}});
 document.querySelectorAll("[data-chg-direction]").forEach(function(b){b.onclick=function(){data.direction=b.dataset.chgDirection;only("[data-chg-direction]",b);save();updateNext(step)}});
 document.querySelectorAll("[data-chg-reversible]").forEach(function(b){b.onclick=function(){data.reversible=b.dataset.chgReversible;if(data.reversible!=="Non, difficilement")data.saferTest="";render()}});
 document.querySelectorAll("#flow input,#flow textarea").forEach(function(x){x.addEventListener("input",function(){capture(step);save();updateNext(step)});x.addEventListener("change",function(){capture(step);save();updateNext(step)})});
 var finish=document.getElementById("chgFinish");if(finish)finish.onclick=finishSession;
 var edit=document.getElementById("chgEdit");if(edit)edit.onclick=function(){stepIndex=1;render()};
}
function finishSession(){var h=history();h.unshift({id:Date.now(),type:"change",createdAt:new Date().toISOString(),decision:data.sentence||"Besoin de changement",priorities:(data.top3||[]).slice(),action:data.action||"",actionDate:data.actionDate||"",learned:"",done:false,domain:data.domain||"",direction:dirLabel(),test:data.test||"",learning:data.learning||"",tenPercent:data.tenPercent||""});localStorage.setItem(HISTORY,JSON.stringify(h));clear();active=false;document.querySelector('[data-tab="journey"]').click()}
document.querySelectorAll("[data-change-start]").forEach(function(b){b.addEventListener("click",function(){start(true)})});
var resume=document.getElementById("resumeBtn");if(resume)resume.addEventListener("click",function(e){if(noOther()&&localStorage.getItem(CHANGE_STORAGE)){e.preventDefault();e.stopImmediatePropagation();start(false)}},{capture:true});
var reset=document.getElementById("resetBtn");if(reset)reset.addEventListener("click",function(e){if(active){e.preventDefault();e.stopImmediatePropagation();if(window.confirm("Recommencer ce parcours ? Tes réponses en cours seront effacées.")){clear();start(true)}}},{capture:true});
document.querySelectorAll("[data-tab]").forEach(function(b){b.addEventListener("click",function(){active=false})});window.addEventListener("resize",sticky);if(read()&&noOther())showResume();
})();