(function(){
"use strict";
var CONF_STORAGE="clarity_v0_confidence_state",DECISION_STORAGE="clarity_v0_state",PRO_STORAGE="clarity_v0_procrastination_state",HISTORY="clarity_v0_history",active=false,stepIndex=0,data={},steps=["intro","situation","area","doubt","fear","mirror","proofs","standard","goodEnough","perspective","experiment","ease","action","summary"];
var areas=["Travail / études","Prendre la parole","Relations","Apparence / image de moi","Compétences","Prendre une décision","Essayer quelque chose de nouveau","Autre"];
var commonDoubts=["Je ne suis pas assez bon(ne)","Je ne suis pas légitime","Je vais décevoir","Les autres sont meilleurs que moi","Je dois être sûr(e) avant d’agir","Si je me trompe, ça dira quelque chose sur moi","Autre"];
function esc(str){return String(str||"").replace(/[&<>"']/g,function(m){return({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"})[m]});}
function nav(disabled){return '<div class="navrow"><button class="secondary" id="confBack" '+(disabled?'disabled':'')+'>Retour</button><button class="cta" id="confNext">Continuer</button></div>';}
function item(t,v){return '<div class="summary-item"><b>'+esc(t)+'</b><span>'+esc(v||"—")+'</span></div>';}
function date(iso){if(!iso)return "";return new Date(iso+"T12:00:00").toLocaleDateString("fr-FR",{day:"numeric",month:"long",year:"numeric"});}
function history(){try{return JSON.parse(localStorage.getItem(HISTORY)||"[]")}catch(e){return[]}}
function read(){try{var raw=localStorage.getItem(CONF_STORAGE);if(!raw)return false;var saved=JSON.parse(raw);data=saved.data||{};stepIndex=Number.isInteger(saved.step)?saved.step:0;if(stepIndex<0||stepIndex>=steps.length)stepIndex=0;return true}catch(e){return false}}
function save(){localStorage.setItem(CONF_STORAGE,JSON.stringify({data:data,step:stepIndex}));resumeCard();}
function clear(){localStorage.removeItem(CONF_STORAGE);data={};stepIndex=0;}
function resumeCard(){if(localStorage.getItem(DECISION_STORAGE)||localStorage.getItem(PRO_STORAGE))return;var card=document.getElementById("resumeCard"),text=document.getElementById("resumeText");if(!card||!text)return;card.classList.remove("hidden");text.textContent=data.situation?"Tu travaillais sur : « "+data.situation+" »":"Tu as un parcours Le Miroir des preuves en cours.";}
function sticky(){var t=document.querySelector(".topbar");if(t)document.documentElement.style.setProperty("--topbar-h",t.offsetHeight+"px");}
function start(fresh){if(fresh){localStorage.removeItem(DECISION_STORAGE);localStorage.removeItem(PRO_STORAGE);clear()}else read();document.querySelectorAll(".screen").forEach(function(s){s.classList.remove("active")});document.getElementById("flow").classList.add("active");document.querySelector(".bottom").classList.add("hidden");document.getElementById("resetBtn").classList.remove("hidden");document.querySelectorAll(".tab").forEach(function(t){t.classList.remove("active")});active=true;render();}
function standardInsight(){if(data.sameStandard==="Non")return "Tu sembles demander davantage à toi-même qu’à une autre personne dans la même situation. Le but n’est pas de baisser tes exigences, mais de les rendre plus réalistes.";if(data.sameStandard==="Oui")return "Ton exigence ressemble à celle que tu appliquerais à quelqu’un d’autre. Vérifions maintenant qu’elle est assez concrète pour guider une action.";return "Comparer tes exigences aide à distinguer un critère utile d’une exigence impossible à satisfaire.";}
function proof(id,title,val,ph){return '<div class="quadrant"><label>'+esc(title)+'</label><textarea data-conf-proof="'+id+'" placeholder="'+esc(ph)+'">'+esc(val||"")+'</textarea></div>';}
function render(){var step=steps[stepIndex],host=document.getElementById("flowContent"),flow=document.getElementById("flow");flow.classList.toggle("sticky-question",step!=="intro"&&step!=="summary");document.getElementById("progress").style.width=Math.round(stepIndex/(steps.length-1)*100)+"%";
if(step==="intro")host.innerHTML='<div class="hero"><div class="eyebrow">Le Miroir des preuves</div><h2>On ne va pas essayer de te convaincre que tu es formidable.</h2><p>On va regarder une situation précise, ce que ton doute affirme et ce que les faits permettent réellement de conclure.</p></div><div class="card soft-green"><b>Objectif</b><p>Passer d’un jugement global sur toi à des preuves concrètes, un niveau “suffisamment bien” et un petit test dans la réalité.</p></div>'+nav(true);
if(step==="situation")host.innerHTML='<div class="hero"><div class="eyebrow">1 · La situation</div><h2>Dans quelle situation doutes-tu de toi en ce moment&nbsp;?</h2><p class="muted">Choisis une scène ou un contexte précis plutôt qu’un jugement général sur toi.</p></div><div class="field"><label>La situation</label><textarea id="confSituation" placeholder="Ex. Je dois présenter mon projet devant mon équipe vendredi">'+esc(data.situation||"")+'</textarea></div>'+nav(false);
if(step==="area")host.innerHTML='<div class="hero"><div class="eyebrow">2 · Le contexte</div><h2>Où ce doute se manifeste-t-il surtout&nbsp;?</h2></div><div class="choices">'+areas.map(function(x,i){return '<button class="choice '+(data.area===x?'selected':'')+'" data-conf-area="'+i+'">'+esc(x)+'</button>'}).join("")+'</div>'+nav(false);
if(step==="doubt")host.innerHTML='<div class="hero"><div class="eyebrow">3 · La phrase du doute</div><h2>Quand le doute parle, qu’est-ce qu’il te dit&nbsp;?</h2><p class="muted">Choisis une phrase proche de ce que tu penses, ou écris la tienne.</p></div><div class="choices">'+commonDoubts.map(function(x,i){return '<button class="choice '+(data.doubtPreset===x?'selected':'')+'" data-conf-doubt="'+i+'">'+esc(x)+'</button>'}).join("")+'</div><div class="field"><label>Ma phrase exacte</label><input id="confDoubtText" type="text" placeholder="Ex. Je ne suis pas assez crédible pour présenter ça" value="'+esc(data.doubtText||"")+'"></div>'+nav(false);
if(step==="fear")host.innerHTML='<div class="hero"><div class="eyebrow">4 · Ce que le doute cherche à éviter</div><h2>Complète : “J’ai peur que les autres découvrent que…”</h2><p class="muted">Pas besoin que ce soit rationnel. On cherche ce que le doute essaie de prévenir.</p></div><div class="field"><textarea id="confFear" placeholder="Ex. …je ne maîtrise pas vraiment le sujet">'+esc(data.fear||"")+'</textarea></div>'+nav(false);
if(step==="mirror")host.innerHTML='<div class="hero"><div class="eyebrow">5 · Le Miroir des preuves</div><h2>Que raconte ton doute — et que peux-tu réellement observer&nbsp;?</h2></div><div class="card coral"><div class="field"><label>Ce que mon doute me raconte</label><textarea id="confStory">'+esc(data.story||data.doubtText||data.doubtPreset||"")+'</textarea></div></div><div class="card soft-green"><div class="field"><label>Ce que je peux réellement observer</label><textarea id="confFacts" placeholder="Faits précis : retours reçus, résultats, expériences…">'+esc(data.facts||"")+'</textarea></div></div>'+nav(false);
if(step==="proofs")host.innerHTML='<div class="hero"><div class="eyebrow">6 · Les preuves disponibles</div><h2>Qu’est-ce que ton doute oublie de compter&nbsp;?</h2><p class="muted">Une ou deux réponses suffisent. Cherche du concret.</p></div><div class="compass">'+proof("success","Une réussite passée",data.success,"Une situation menée à bien…")+proof("strength","Une qualité reconnue",data.strength,"Quelque chose qu’on reconnaît chez toi…")+proof("skill","Une compétence développée",data.skill,"Ce que tu sais mieux faire qu’avant…")+proof("crossed","Une difficulté traversée",data.crossed,"Un moment difficile que tu as géré…")+'</div>'+nav(false);
if(step==="standard")host.innerHTML='<div class="hero"><div class="eyebrow">7 · Ton niveau d’exigence</div><h2>Qu’est-ce que tu attends de toi pour te sentir “à la hauteur” ici&nbsp;?</h2></div><div class="field"><textarea id="confStandard" placeholder="Ex. répondre parfaitement à toutes les questions…">'+esc(data.standard||"")+'</textarea></div><div class="divider"></div><h3>Attendrais-tu exactement la même chose d’une personne que tu apprécies dans la même situation&nbsp;?</h3><div class="choices">'+["Oui","Non","Je ne sais pas"].map(function(x){return '<button class="choice '+(data.sameStandard===x?'selected':'')+'" data-conf-standard="'+esc(x)+'">'+esc(x)+'</button>'}).join("")+'</div>'+(data.sameStandard?'<div class="insight">'+standardInsight()+'</div>':'')+nav(false);
if(step==="goodEnough")host.innerHTML='<div class="hero"><div class="eyebrow">8 · Suffisamment bien</div><h2>À quoi ressemblerait une version “suffisamment bien” de cette situation&nbsp;?</h2><p class="muted">Pas parfaite. Assez solide pour agir et apprendre.</p></div><div class="field"><textarea id="confGoodEnough" placeholder="Ex. expliquer mes 3 idées principales clairement…">'+esc(data.goodEnough||"")+'</textarea></div>'+nav(false);
if(step==="perspective")host.innerHTML='<div class="hero"><div class="eyebrow">9 · Changer de point de vue</div><h2>Si une personne que tu estimes vivait la même situation, que lui dirais-tu&nbsp;?</h2></div><div class="field"><textarea id="confPerspective" placeholder="Ex. Tu n’as pas besoin de tout savoir pour présenter ce que tu as préparé">'+esc(data.perspective||"")+'</textarea></div>'+nav(false);
if(step==="experiment")host.innerHTML='<div class="hero"><div class="eyebrow">10 · Tester plutôt que croire</div><h2>Quel petit test pourrait te donner une preuve nouvelle dans la réalité&nbsp;?</h2><p class="muted">Prendre la parole une fois, demander un retour, envoyer une première version…</p></div><div class="field"><label>Mon test</label><input id="confExperiment" type="text" placeholder="Ex. Présenter mes 3 premières slides à un collègue" value="'+esc(data.experiment||"")+'"></div>'+nav(false);
if(step==="ease"){var e=Number(data.ease||0);host.innerHTML='<div class="hero"><div class="eyebrow">11 · Faisabilité</div><h2>À quel point ce test te paraît faisable&nbsp;?</h2><p class="muted">1 = je vais probablement l’éviter · 5 = je peux réellement le tenter.</p></div><div class="chips">'+[1,2,3,4,5].map(function(n){return '<button class="chip '+(e===n?'selected':'')+'" data-conf-ease="'+n+'">'+n+'</button>'}).join("")+'</div>'+(e>0&&e<4?'<div class="insight">Le test est encore trop exposant. Réduis-le jusqu’à ce qu’il devienne crédible.</div><div class="field"><label>Version plus petite</label><input id="confSmaller" type="text" placeholder="Ex. Répéter seulement l’introduction devant une personne" value="'+esc(data.smallerExperiment||"")+'"></div>':'')+nav(false)}
if(step==="action"){var proposed=(data.ease&&data.ease<4&&data.smallerExperiment)?data.smallerExperiment:data.experiment;host.innerHTML='<div class="hero"><div class="eyebrow">12 · Prochain pas</div><h2>Quand vas-tu faire ce test&nbsp;?</h2><p class="muted">Le but n’est pas de “devenir confiant(e)”. Le but est de recueillir une preuve nouvelle.</p></div><div class="card soft-green"><label>Action</label><input id="confAction" type="text" value="'+esc(data.action||proposed||"")+'" placeholder="Mon test concret"></div><div class="field"><label>Quand ?</label><input id="confDate" type="date" value="'+esc(data.actionDate||"")+'"></div>'+nav(false)}
if(step==="summary")host.innerHTML='<div class="hero"><div class="eyebrow">Ton Miroir des preuves</div><h2>Ton doute est une hypothèse. Tes prochaines preuves viendront surtout de ce que tu testes.</h2></div><div class="summary-grid">'+item("Situation",data.situation)+item("Contexte",data.area)+item("Ce que le doute raconte",data.story||data.doubtText||data.doubtPreset)+item("Ce que tu observes",data.facts)+item("Réussite passée",data.success)+item("Compétence développée",data.skill)+item("Suffisamment bien",data.goodEnough)+item("Ce que tu dirais à quelqu’un d’autre",data.perspective)+'</div><div class="card soft-green"><div class="eyebrow">Prochain test</div><h3>'+esc(data.action||"À définir")+'</h3><p>'+(data.actionDate?date(data.actionDate):"Sans date définie")+'</p></div><div class="insight">Au suivi, la bonne question ne sera pas “Est-ce que tu as enfin confiance ?”, mais <b>“Qu’est-ce que ce test t’a appris ?”</b></div><button class="cta" id="confFinish">Enregistrer dans Mon parcours</button><div style="height:10px"></div><button class="secondary" id="confEdit">Modifier une réponse</button>';
bind(step);updateNext(step);sticky();save();requestAnimationFrame(function(){window.scrollTo(0,0)});}
function capture(step){function v(id){var x=document.getElementById(id);return x?x.value.trim():""}if(step==="situation")data.situation=v("confSituation");if(step==="doubt")data.doubtText=v("confDoubtText");if(step==="fear")data.fear=v("confFear");if(step==="mirror"){data.story=v("confStory");data.facts=v("confFacts")}if(step==="proofs")document.querySelectorAll("[data-conf-proof]").forEach(function(x){data[x.dataset.confProof]=x.value.trim()});if(step==="standard")data.standard=v("confStandard");if(step==="goodEnough")data.goodEnough=v("confGoodEnough");if(step==="perspective")data.perspective=v("confPerspective");if(step==="experiment")data.experiment=v("confExperiment");if(step==="ease")data.smallerExperiment=v("confSmaller");if(step==="action"){data.action=v("confAction");data.actionDate=v("confDate")}}
function valid(step){if(step==="situation")return !!data.situation;if(step==="area")return !!data.area;if(step==="doubt")return !!data.doubtPreset||!!data.doubtText;if(step==="fear")return !!data.fear;if(step==="mirror")return !!data.story&&!!data.facts;if(step==="proofs")return !!data.success||!!data.strength||!!data.skill||!!data.crossed;if(step==="standard")return !!data.standard&&!!data.sameStandard;if(step==="goodEnough")return !!data.goodEnough;if(step==="perspective")return !!data.perspective;if(step==="experiment")return !!data.experiment;if(step==="ease")return !!data.ease&&(data.ease>=4||!!data.smallerExperiment);if(step==="action")return !!data.action;return true}
function updateNext(step){var n=document.getElementById("confNext");if(!n)return;capture(step);n.disabled=!valid(step)}
function only(sel,b){document.querySelectorAll(sel).forEach(function(x){x.classList.remove("selected")});b.classList.add("selected")}
function bind(step){var back=document.getElementById("confBack"),next=document.getElementById("confNext");if(back)back.onclick=function(){capture(step);if(stepIndex>0){stepIndex--;render()}};if(next)next.onclick=function(){capture(step);if(valid(step)){stepIndex++;render()}};document.querySelectorAll("[data-conf-area]").forEach(function(b){b.onclick=function(){data.area=areas[Number(b.dataset.confArea)];only("[data-conf-area]",b);save();updateNext(step)}});document.querySelectorAll("[data-conf-doubt]").forEach(function(b){b.onclick=function(){data.doubtPreset=commonDoubts[Number(b.dataset.confDoubt)];if(!data.doubtText||commonDoubts.indexOf(data.doubtText)>=0)data.doubtText=data.doubtPreset;render()}});document.querySelectorAll("[data-conf-standard]").forEach(function(b){b.onclick=function(){data.sameStandard=b.dataset.confStandard;render()}});document.querySelectorAll("[data-conf-ease]").forEach(function(b){b.onclick=function(){data.ease=Number(b.dataset.confEase);render()}});document.querySelectorAll("#flow input,#flow textarea").forEach(function(x){x.addEventListener("input",function(){capture(step);save();updateNext(step)});x.addEventListener("change",function(){capture(step);save();updateNext(step)})});var finish=document.getElementById("confFinish");if(finish)finish.onclick=finishSession;var edit=document.getElementById("confEdit");if(edit)edit.onclick=function(){stepIndex=1;render()}}
function finishSession(){var h=history();h.unshift({id:Date.now(),type:"confidence",createdAt:new Date().toISOString(),decision:data.situation||"Confiance en soi",priorities:[data.area||"Confiance en soi"],action:data.action||"",actionDate:data.actionDate||"",learned:"",done:false,doubt:data.story||data.doubtText||data.doubtPreset||"",facts:data.facts||"",goodEnough:data.goodEnough||"",experiment:data.experiment||""});localStorage.setItem(HISTORY,JSON.stringify(h));clear();active=false;document.querySelector('[data-tab="journey"]').click()}
document.querySelectorAll("[data-confidence-start]").forEach(function(b){b.addEventListener("click",function(){start(true)})});
document.querySelectorAll('[data-start="decision"]').forEach(function(b){b.addEventListener("click",function(){localStorage.removeItem(CONF_STORAGE)},{capture:true})});document.querySelectorAll("[data-pro-start]").forEach(function(b){b.addEventListener("click",function(){localStorage.removeItem(CONF_STORAGE)},{capture:true})});
var resume=document.getElementById("resumeBtn");if(resume)resume.addEventListener("click",function(e){if(!localStorage.getItem(DECISION_STORAGE)&&!localStorage.getItem(PRO_STORAGE)&&localStorage.getItem(CONF_STORAGE)){e.preventDefault();e.stopImmediatePropagation();start(false)}},{capture:true});
var reset=document.getElementById("resetBtn");if(reset)reset.addEventListener("click",function(e){if(active){e.preventDefault();e.stopImmediatePropagation();if(window.confirm("Recommencer ce parcours ? Tes réponses en cours seront effacées.")){clear();start(true)}}},{capture:true});
var erase=document.getElementById("eraseBtn");if(erase)erase.addEventListener("click",function(e){e.preventDefault();e.stopImmediatePropagation();if(window.confirm("Effacer toutes les données locales de Clarity sur cet appareil ?")){localStorage.removeItem(DECISION_STORAGE);localStorage.removeItem(PRO_STORAGE);localStorage.removeItem(CONF_STORAGE);localStorage.removeItem(HISTORY);window.location.reload()}},{capture:true});
document.querySelectorAll("[data-tab]").forEach(function(b){b.addEventListener("click",function(){active=false})});window.addEventListener("resize",sticky);if(read()&&!localStorage.getItem(DECISION_STORAGE)&&!localStorage.getItem(PRO_STORAGE))resumeCard();
})();