(function(){
"use strict";
var FAIL_STORAGE="clarity_v0_failure_state",HISTORY="clarity_v0_history";
var OTHER=["clarity_v0_state","clarity_v0_confidence_state","clarity_v0_procrastination_state","clarity_v0_lost_state","clarity_v0_rumination_state","clarity_v0_limits_state"];
var active=false,stepIndex=0,data={};
var steps=["intro","attempt","fear","scenario","probability","recoverability","resources","neverTry","experiment","threeScenarios","identity","riskBudget","action","summary"];
var probabilities=["Très peu probable","Peu probable","Possible","Probable","Très probable","Je ne sais pas"];
var recoverabilities=["Très difficile à réparer","Réparable avec beaucoup d’effort","Plutôt réparable","Facilement réversible","Je ne sais pas encore"];
var riskLevels=["Très faible","Faible","Modéré","Élevé"];
function esc(s){return String(s||"").replace(/[&<>"']/g,function(m){return({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"})[m]});}
function nav(disabled){return '<div class="navrow"><button class="secondary" id="failBack" '+(disabled?'disabled':'')+'>Retour</button><button class="cta" id="failNext">Continuer</button></div>';}
function item(t,v){return '<div class="summary-item"><b>'+esc(t)+'</b><span>'+esc(v||"—")+'</span></div>';}
function fmtDate(iso){if(!iso)return "";return new Date(iso+"T12:00:00").toLocaleDateString("fr-FR",{day:"numeric",month:"long",year:"numeric"});}
function history(){try{return JSON.parse(localStorage.getItem(HISTORY)||"[]")}catch(e){return[]}}
function noOther(){return OTHER.every(function(k){return !localStorage.getItem(k)})}
function clearOthers(){OTHER.forEach(function(k){localStorage.removeItem(k)})}
function read(){try{var raw=localStorage.getItem(FAIL_STORAGE);if(!raw)return false;var s=JSON.parse(raw);data=s.data||{};stepIndex=Number.isInteger(s.step)?s.step:0;if(stepIndex<0||stepIndex>=steps.length)stepIndex=0;return true}catch(e){return false}}
function save(){localStorage.setItem(FAIL_STORAGE,JSON.stringify({data:data,step:stepIndex}));showResume();}
function clear(){localStorage.removeItem(FAIL_STORAGE);data={};stepIndex=0;}
function showResume(){if(!noOther())return;var c=document.getElementById("resumeCard"),t=document.getElementById("resumeText");if(!c||!t)return;c.classList.remove("hidden");t.textContent=data.attempt?"Tu travaillais sur : « "+data.attempt+" »":"Tu as un parcours Le Test du scénario en cours.";}
function sticky(){var t=document.querySelector(".topbar");if(t)document.documentElement.style.setProperty("--topbar-h",t.offsetHeight+"px");}
function start(fresh){if(fresh){clearOthers();clear()}else read();document.querySelectorAll(".screen").forEach(function(s){s.classList.remove("active")});document.getElementById("flow").classList.add("active");document.querySelector(".bottom").classList.add("hidden");document.getElementById("resetBtn").classList.remove("hidden");document.querySelectorAll(".tab").forEach(function(t){t.classList.remove("active")});active=true;render();}
function riskInsight(){if(data.recoverability==="Très difficile à réparer")return "Quand une conséquence serait vraiment difficile à réparer, l’objectif n’est pas de te pousser à prendre plus de risque. Cherche plutôt une version du test qui réduit l’exposition.";if(data.recoverability==="Facilement réversible"||data.recoverability==="Plutôt réparable")return "Une conséquence réversible peut parfois être explorée par un petit test plutôt que par une décision définitive.";return "Distinguer ce qui est grave de ce qui est réparable aide à calibrer le risque au lieu de traiter toute erreur comme une catastrophe.";}
function proposedAction(){return data.smallerExperiment||data.experiment||"";}
function render(){
 var step=steps[stepIndex],host=document.getElementById("flowContent"),flow=document.getElementById("flow");
 flow.classList.toggle("sticky-question",step!=="intro"&&step!=="summary");
 document.getElementById("progress").style.width=Math.round(stepIndex/(steps.length-1)*100)+"%";
 if(step==="intro")host.innerHTML='<div class="hero"><div class="eyebrow">Le Test du scénario</div><h2>La peur d’échouer mélange souvent plusieurs risques en un seul bloc.</h2><p>On va préciser ce que tu crains, regarder ce qui est probable et récupérable, puis construire un essai à risque limité.</p></div><div class="card soft-green"><b>Objectif</b><p>Passer de “je ne peux pas me permettre d’échouer” à un scénario concret, un risque calibré et une expérience qui permet d’apprendre.</p></div>'+nav(true);
 if(step==="attempt")host.innerHTML='<div class="hero"><div class="eyebrow">1 · Ce que tu aimerais tenter</div><h2>Qu’est-ce que tu aimerais faire si la peur d’échouer prenait un peu moins de place&nbsp;?</h2></div><div class="field"><label>Ce que j’aimerais tenter</label><textarea id="failAttempt" placeholder="Ex. proposer mon projet, candidater à un poste, lancer une offre, parler en public…">'+esc(data.attempt||"")+'</textarea></div>'+nav(false);
 if(step==="fear")host.innerHTML='<div class="hero"><div class="eyebrow">2 · L’échec redouté</div><h2>Si tu “échouais”, qu’est-ce que cela voudrait dire concrètement&nbsp;?</h2><p class="muted">Décris un résultat observable, pas un jugement global sur toi.</p></div><div class="field"><textarea id="failFear" placeholder="Ex. recevoir un refus, perdre 500 €, faire une présentation moyenne…">'+esc(data.fear||"")+'</textarea></div>'+nav(false);
 if(step==="scenario")host.innerHTML='<div class="hero"><div class="eyebrow">3 · La conséquence réelle</div><h2>Si ce scénario arrivait, qu’est-ce qui se passerait ensuite&nbsp;?</h2><p class="muted">Quelles conséquences seraient réelles dans les jours ou semaines qui suivent ?</p></div><div class="field"><textarea id="failConsequence" placeholder="Ex. je serais déçu(e), je devrais revoir le projet, je perdrais du temps…">'+esc(data.consequence||"")+'</textarea></div>'+nav(false);
 if(step==="probability")host.innerHTML='<div class="hero"><div class="eyebrow">4 · Probabilité</div><h2>Avec les informations que tu as aujourd’hui, à quel point ce scénario te paraît probable&nbsp;?</h2></div><div class="choices">'+probabilities.map(function(x){return '<button class="choice '+(data.probability===x?'selected':'')+'" data-fail-probability="'+esc(x)+'">'+esc(x)+'</button>'}).join("")+'</div>'+nav(false);
 if(step==="recoverability")host.innerHTML='<div class="hero"><div class="eyebrow">5 · Réparabilité</div><h2>Si ça arrivait, à quel point pourrais-tu t’en remettre ou corriger la situation&nbsp;?</h2></div><div class="choices">'+recoverabilities.map(function(x){return '<button class="choice '+(data.recoverability===x?'selected':'')+'" data-fail-recover="'+esc(x)+'">'+esc(x)+'</button>'}).join("")+'</div>'+(data.recoverability?'<div class="insight">'+riskInsight()+'</div>':'')+nav(false);
 if(step==="resources")host.innerHTML='<div class="hero"><div class="eyebrow">6 · Tes ressources</div><h2>Qu’est-ce qui t’aiderait à gérer la situation si ça se passait moins bien que prévu&nbsp;?</h2><p class="muted">Compétences, argent de côté, personne à appeler, possibilité de recommencer, plan B…</p></div><div class="field"><textarea id="failResources" placeholder="Ex. demander un retour, corriger puis réessayer, limiter mon budget, garder une autre option…">'+esc(data.resources||"")+'</textarea></div>'+nav(false);
 if(step==="neverTry")host.innerHTML='<div class="hero"><div class="eyebrow">7 · Le risque de ne jamais essayer</div><h2>Si tu évites cette tentative pendant un an, qu’est-ce que cela pourrait te coûter&nbsp;?</h2><p class="muted">Il existe parfois un risque à agir — et aussi un risque à rester immobile.</p></div><div class="field"><textarea id="failNever" placeholder="Ex. rester frustré(e), ne jamais savoir, perdre une occasion, continuer à me sous-estimer…">'+esc(data.neverTry||"")+'</textarea></div>'+nav(false);
 if(step==="experiment")host.innerHTML='<div class="hero"><div class="eyebrow">8 · Transformer le saut en test</div><h2>Quelle version plus petite et moins risquée pourrais-tu tester&nbsp;?</h2><p class="muted">Le test doit produire de l’information sans t’obliger à tout miser.</p></div><div class="field"><label>Mon expérience à faible risque</label><input id="failExperiment" type="text" placeholder="Ex. présenter l’idée à 3 personnes avant de la lancer" value="'+esc(data.experiment||"")+'"></div>'+nav(false);
 if(step==="threeScenarios")host.innerHTML='<div class="hero"><div class="eyebrow">9 · Trois scénarios</div><h2>Regarde l’essai sans laisser le pire scénario prendre toute la place.</h2></div><div class="card coral"><div class="field"><label>Le pire raisonnable</label><textarea id="failWorst" placeholder="Ce qui pourrait vraiment mal se passer, sans catastrophe imaginaire…">'+esc(data.worst||"")+'</textarea></div></div><div class="card cream"><div class="field"><label>Le plus probable</label><textarea id="failLikely" placeholder="Ce qui semble le plus plausible…">'+esc(data.likely||"")+'</textarea></div></div><div class="card soft-green"><div class="field"><label>Le meilleur raisonnable</label><textarea id="failBest" placeholder="Ce qui pourrait bien se passer de façon réaliste…">'+esc(data.best||"")+'</textarea></div></div>'+nav(false);
 if(step==="identity")host.innerHTML='<div class="hero"><div class="eyebrow">10 · Résultat ≠ identité</div><h2>Si ce test ne fonctionne pas, qu’est-ce que cela prouverait réellement — et qu’est-ce que cela ne prouverait pas sur toi&nbsp;?</h2></div><div class="card cream"><div class="field"><label>Ce que ça m’apprendrait</label><textarea id="failLearning" placeholder="Ex. cette approche ne convainc pas encore, il manque une compétence, le timing n’est pas bon…">'+esc(data.learning||"")+'</textarea></div></div><div class="card soft-green"><div class="field"><label>Ce que ça ne prouverait pas sur moi</label><textarea id="failNotIdentity" placeholder="Ex. que je suis incapable, que je ne réussirai jamais…">'+esc(data.notIdentity||"")+'</textarea></div></div>'+nav(false);
 if(step==="riskBudget"){
   var needsSmaller=data.riskLevel==="Élevé"||data.recoverability==="Très difficile à réparer";
   host.innerHTML='<div class="hero"><div class="eyebrow">11 · Ton budget de risque</div><h2>Quel niveau de risque ce test représente-t-il pour toi&nbsp;?</h2><p class="muted">Pense au temps, à l’argent, à l’exposition et aux conséquences concrètes.</p></div><div class="choices">'+riskLevels.map(function(x){return '<button class="choice '+(data.riskLevel===x?'selected':'')+'" data-fail-risk="'+x+'">'+x+'</button>'}).join("")+'</div>'+(needsSmaller?'<div class="insight">Ce test semble encore trop exposant par rapport à ce que tu veux protéger. Réduis-le avant de continuer.</div><div class="field"><label>Version moins risquée</label><input id="failSmaller" type="text" placeholder="Ex. tester auprès d’une seule personne, limiter le budget, faire une version temporaire…" value="'+esc(data.smallerExperiment||"")+'"></div>':'')+nav(false);
 }
 if(step==="action"){var p=proposedAction();host.innerHTML='<div class="hero"><div class="eyebrow">12 · Prochain pas</div><h2>Quel test vas-tu réellement faire&nbsp;?</h2><p class="muted">Le contraire de l’échec n’est pas toujours la réussite. Parfois, c’est l’apprentissage.</p></div><div class="card soft-green"><label>Mon test</label><input id="failAction" type="text" value="'+esc(data.action||p)+'" placeholder="Mon expérience à faible risque"></div><div class="field"><label>Quand ?</label><input id="failDate" type="date" value="'+esc(data.actionDate||"")+'"></div>'+nav(false)}
 if(step==="summary")host.innerHTML='<div class="hero"><div class="eyebrow">Ton Test du scénario</div><h2>Tu n’as pas supprimé le risque. Tu l’as rendu visible et calibré.</h2></div><div class="summary-grid">'+item("Ce que tu veux tenter",data.attempt)+item("Échec redouté",data.fear)+item("Conséquence réelle",data.consequence)+item("Probabilité",data.probability)+item("Réparabilité",data.recoverability)+item("Tes ressources",data.resources)+item("Coût de ne pas essayer",data.neverTry)+item("Pire raisonnable",data.worst)+item("Plus probable",data.likely)+item("Meilleur raisonnable",data.best)+item("Ce que ça t’apprendrait",data.learning)+item("Ce que ça ne prouverait pas sur toi",data.notIdentity)+'</div><div class="card soft-green"><div class="eyebrow">Expérience</div><h3>'+esc(data.action||"À définir")+'</h3><p>'+(data.actionDate?fmtDate(data.actionDate):"Sans date définie")+'</p></div><div class="insight">L’objectif du test n’est pas de garantir la réussite. Il est de rendre le risque acceptable et d’obtenir une information que l’évitement ne peut pas te donner.</div><button class="cta" id="failFinish">Enregistrer dans Mon parcours</button><div style="height:10px"></div><button class="secondary" id="failEdit">Modifier une réponse</button>';
 bind(step);updateNext(step);sticky();save();requestAnimationFrame(function(){window.scrollTo(0,0)});
}
function capture(step){function v(id){var e=document.getElementById(id);return e?e.value.trim():""}if(step==="attempt")data.attempt=v("failAttempt");if(step==="fear")data.fear=v("failFear");if(step==="scenario")data.consequence=v("failConsequence");if(step==="resources")data.resources=v("failResources");if(step==="neverTry")data.neverTry=v("failNever");if(step==="experiment")data.experiment=v("failExperiment");if(step==="threeScenarios"){data.worst=v("failWorst");data.likely=v("failLikely");data.best=v("failBest")}if(step==="identity"){data.learning=v("failLearning");data.notIdentity=v("failNotIdentity")}if(step==="riskBudget")data.smallerExperiment=v("failSmaller");if(step==="action"){data.action=v("failAction");data.actionDate=v("failDate")}}
function valid(step){if(step==="attempt")return !!data.attempt;if(step==="fear")return !!data.fear;if(step==="scenario")return !!data.consequence;if(step==="probability")return !!data.probability;if(step==="recoverability")return !!data.recoverability;if(step==="resources")return !!data.resources;if(step==="neverTry")return !!data.neverTry;if(step==="experiment")return !!data.experiment;if(step==="threeScenarios")return !!data.worst&&!!data.likely&&!!data.best;if(step==="identity")return !!data.learning&&!!data.notIdentity;if(step==="riskBudget"){if(!data.riskLevel)return false;return !(data.riskLevel==="Élevé"||data.recoverability==="Très difficile à réparer")||!!data.smallerExperiment}if(step==="action")return !!data.action;return true}
function updateNext(step){var n=document.getElementById("failNext");if(!n)return;capture(step);n.disabled=!valid(step)}
function only(sel,b){document.querySelectorAll(sel).forEach(function(x){x.classList.remove("selected")});b.classList.add("selected")}
function bind(step){var back=document.getElementById("failBack"),next=document.getElementById("failNext");if(back)back.onclick=function(){capture(step);if(stepIndex>0){stepIndex--;render()}};if(next)next.onclick=function(){capture(step);if(valid(step)){stepIndex++;render()}};
 document.querySelectorAll("[data-fail-probability]").forEach(function(b){b.onclick=function(){data.probability=b.dataset.failProbability;only("[data-fail-probability]",b);save();updateNext(step)}});
 document.querySelectorAll("[data-fail-recover]").forEach(function(b){b.onclick=function(){data.recoverability=b.dataset.failRecover;render()}});
 document.querySelectorAll("[data-fail-risk]").forEach(function(b){b.onclick=function(){data.riskLevel=b.dataset.failRisk;if(data.riskLevel!=="Élevé"&&data.recoverability!=="Très difficile à réparer")data.smallerExperiment="";render()}});
 document.querySelectorAll("#flow input,#flow textarea").forEach(function(x){x.addEventListener("input",function(){capture(step);save();updateNext(step)});x.addEventListener("change",function(){capture(step);save();updateNext(step)})});
 var finish=document.getElementById("failFinish");if(finish)finish.onclick=finishSession;var edit=document.getElementById("failEdit");if(edit)edit.onclick=function(){stepIndex=1;render()};
}
function finishSession(){var h=history();h.unshift({id:Date.now(),type:"failure",createdAt:new Date().toISOString(),decision:data.attempt||"Peur d’échouer",priorities:["Risque : "+(data.riskLevel||"à calibrer")],action:data.action||"",actionDate:data.actionDate||"",learned:"",done:false,fear:data.fear||"",probability:data.probability||"",recoverability:data.recoverability||"",experiment:data.action||data.experiment||""});localStorage.setItem(HISTORY,JSON.stringify(h));clear();active=false;document.querySelector('[data-tab="journey"]').click()}
document.querySelectorAll("[data-failure-start]").forEach(function(b){b.addEventListener("click",function(){start(true)})});
var resume=document.getElementById("resumeBtn");if(resume)resume.addEventListener("click",function(e){if(noOther()&&localStorage.getItem(FAIL_STORAGE)){e.preventDefault();e.stopImmediatePropagation();start(false)}},{capture:true});
var reset=document.getElementById("resetBtn");if(reset)reset.addEventListener("click",function(e){if(active){e.preventDefault();e.stopImmediatePropagation();if(window.confirm("Recommencer ce parcours ? Tes réponses en cours seront effacées.")){clear();start(true)}}},{capture:true});
document.querySelectorAll("[data-tab]").forEach(function(b){b.addEventListener("click",function(){active=false})});window.addEventListener("resize",sticky);if(read()&&noOther())showResume();
})();