(function(){
"use strict";
var LOST_STORAGE="clarity_v0_lost_state",DECISION_STORAGE="clarity_v0_state",PRO_STORAGE="clarity_v0_procrastination_state",CONF_STORAGE="clarity_v0_confidence_state",HISTORY="clarity_v0_history";
var active=false,stepIndex=0,data={};
var steps=["intro","area","context","map","focus","anchors","missing","moreLess","direction","week","action","summary"];
var areas=["Travail / études","Relations","Famille","Santé / énergie","Temps / rythme de vie","Lieu de vie","Argent / sécurité","Sens / direction générale","Plusieurs domaines à la fois"];
var directions=["Avoir plus de temps pour moi","Repenser mon travail ou mes études","Reprendre une activité qui me fait du bien","Alléger certains engagements","Retrouver plus de lien avec les autres","Apprendre ou explorer quelque chose","Mettre de l’ordre dans une situation concrète","Je ne sais pas encore — je veux seulement tester une piste"];
function esc(s){return String(s||"").replace(/[&<>"']/g,function(m){return({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"})[m]});}
function nav(disabled){return '<div class="navrow"><button class="secondary" id="lostBack" '+(disabled?'disabled':'')+'>Retour</button><button class="cta" id="lostNext">Continuer</button></div>';}
function item(t,v){return '<div class="summary-item"><b>'+esc(t)+'</b><span>'+esc(v||"—")+'</span></div>';}
function fmtDate(iso){if(!iso)return "";return new Date(iso+"T12:00:00").toLocaleDateString("fr-FR",{day:"numeric",month:"long",year:"numeric"});}
function history(){try{return JSON.parse(localStorage.getItem(HISTORY)||"[]")}catch(e){return[]}}
function read(){try{var raw=localStorage.getItem(LOST_STORAGE);if(!raw)return false;var s=JSON.parse(raw);data=s.data||{};stepIndex=Number.isInteger(s.step)?s.step:0;if(stepIndex<0||stepIndex>=steps.length)stepIndex=0;return true}catch(e){return false}}
function save(){localStorage.setItem(LOST_STORAGE,JSON.stringify({data:data,step:stepIndex}));showResume();}
function clear(){localStorage.removeItem(LOST_STORAGE);data={};stepIndex=0;}
function noOther(){return !localStorage.getItem(DECISION_STORAGE)&&!localStorage.getItem(PRO_STORAGE)&&!localStorage.getItem(CONF_STORAGE)}
function showResume(){if(!noOther())return;var c=document.getElementById("resumeCard"),t=document.getElementById("resumeText");if(!c||!t)return;c.classList.remove("hidden");t.textContent=data.context?"Tu cherchais une direction autour de : « "+data.context+" »":"Tu as un parcours La Carte des priorités en cours.";}
function sticky(){var t=document.querySelector(".topbar");if(t)document.documentElement.style.setProperty("--topbar-h",t.offsetHeight+"px");}
function start(fresh){if(fresh){localStorage.removeItem(DECISION_STORAGE);localStorage.removeItem(PRO_STORAGE);localStorage.removeItem(CONF_STORAGE);clear()}else read();document.querySelectorAll(".screen").forEach(function(s){s.classList.remove("active")});document.getElementById("flow").classList.add("active");document.querySelector(".bottom").classList.add("hidden");document.getElementById("resetBtn").classList.remove("hidden");document.querySelectorAll(".tab").forEach(function(t){t.classList.remove("active")});active=true;render();}
function mapBox(id,title,klass,placeholder){return '<div class="card '+klass+'"><div class="field"><label>'+esc(title)+'</label><textarea id="'+id+'" placeholder="'+esc(placeholder)+'">'+esc(data[id]||"")+'</textarea></div></div>';}
function render(){
 var step=steps[stepIndex],host=document.getElementById("flowContent"),flow=document.getElementById("flow");
 flow.classList.toggle("sticky-question",step!=="intro"&&step!=="summary");
 document.getElementById("progress").style.width=Math.round(stepIndex/(steps.length-1)*100)+"%";
 if(step==="intro")host.innerHTML='<div class="hero"><div class="eyebrow">La Carte des priorités</div><h2>Tu n’as pas besoin de savoir exactement où aller.</h2><p>On va d’abord regarder ce qui te nourrit, ce qui t’épuise et ce qui compte assez pour mériter un petit mouvement.</p></div><div class="card soft-green"><b>Objectif</b><p>Passer de “je suis perdu(e)” à une direction provisoire et un test concret pour la semaine qui vient.</p></div>'+nav(true);
 if(step==="area")host.innerHTML='<div class="hero"><div class="eyebrow">1 · Où ça se brouille</div><h2>Dans quel domaine te sens-tu le plus perdu(e) aujourd’hui&nbsp;?</h2></div><div class="choices">'+areas.map(function(x,i){return '<button class="choice '+(data.area===x?'selected':'')+'" data-lost-area="'+i+'">'+esc(x)+'</button>'}).join("")+'</div>'+nav(false);
 if(step==="context")host.innerHTML='<div class="hero"><div class="eyebrow">2 · Le contexte</div><h2>Qu’est-ce qui te fait dire que tu es perdu(e) en ce moment&nbsp;?</h2><p class="muted">Décris ce qui a changé, ce qui manque ou ce qui ne fonctionne plus. Pas besoin d’expliquer toute ta vie.</p></div><div class="field"><textarea id="lostContext" placeholder="Ex. Mon travail ne me convient plus mais je ne sais pas vers quoi aller…">'+esc(data.context||"")+'</textarea></div><div class="field"><label>Depuis quand environ ? <span class="muted">(facultatif)</span></label><input id="lostSince" type="text" placeholder="Ex. depuis quelques mois" value="'+esc(data.since||"")+'"></div>'+nav(false);
 if(step==="map")host.innerHTML='<div class="hero"><div class="eyebrow">3 · Ta Carte des priorités</div><h2>Regarde ta situation sous quatre angles.</h2><p class="muted">Écris quelques mots dans chaque zone. Tu ne cherches pas encore une solution.</p></div>'+mapBox("givesEnergy","Ce qui me fait du bien / me donne de l’énergie","soft-green","Personnes, activités, moments, environnements…")+mapBox("drains","Ce qui m’épuise","coral","Ce qui prend beaucoup d’énergie ou crée de la tension…")+mapBox("matters","Ce qui compte vraiment","cream","Ce que tu veux protéger ou retrouver…")+mapBox("canWait","Ce qui peut attendre","","Ce qui n’a pas besoin d’être résolu maintenant…")+nav(false);
 if(step==="focus")host.innerHTML='<div class="hero"><div class="eyebrow">4 · Ce qui prend toute la place</div><h2>Qu’est-ce qui occupe le plus ton esprit en ce moment&nbsp;?</h2><p class="muted">Et pourquoi cette chose prend-elle autant de place ?</p></div><div class="field"><label>Ce qui prend le plus de place</label><textarea id="lostFocus" placeholder="Ex. mon travail, parce que j’y pense dès le réveil…">'+esc(data.focus||"")+'</textarea></div>'+nav(false);
 if(step==="anchors")host.innerHTML='<div class="hero"><div class="eyebrow">5 · Tes points d’appui</div><h2>Quelles sont 1 à 3 choses que tu veux absolument préserver&nbsp;?</h2><p class="muted">Même dans une période floue, tout n’est pas à remettre en question.</p></div><div class="field"><label>Mes repères à préserver</label><textarea id="lostAnchors" placeholder="Ex. ma relation, du temps pour mes enfants, ma stabilité financière…">'+esc(data.anchors||"")+'</textarea></div>'+nav(false);
 if(step==="missing")host.innerHTML='<div class="hero"><div class="eyebrow">6 · Ce qui manque</div><h2>Parmi ce qui compte pour toi, qu’est-ce qui est le moins présent aujourd’hui&nbsp;?</h2></div><div class="field"><textarea id="lostMissing" placeholder="Ex. du temps, du sens, du mouvement, des relations stimulantes…">'+esc(data.missing||"")+'</textarea></div>'+nav(false);
 if(step==="moreLess")host.innerHTML='<div class="hero"><div class="eyebrow">7 · Une direction simple</div><h2>Si les prochaines semaines allaient un peu mieux, de quoi y aurait-il plus — et moins&nbsp;?</h2></div><div class="card soft-green"><div class="field"><label>Plus de…</label><textarea id="lostMore" placeholder="Ex. calme, mouvement, autonomie, temps dehors…">'+esc(data.more||"")+'</textarea></div></div><div class="card coral"><div class="field"><label>Moins de…</label><textarea id="lostLess" placeholder="Ex. réunions, obligations, écrans, décisions urgentes…">'+esc(data.less||"")+'</textarea></div></div>'+nav(false);
 if(step==="direction")host.innerHTML='<div class="hero"><div class="eyebrow">8 · La direction à explorer</div><h2>Quelle direction mérite un petit test en premier&nbsp;?</h2><p class="muted">Ce n’est pas un engagement définitif. C’est une piste à explorer.</p></div><div class="choices">'+directions.map(function(x,i){return '<button class="choice '+(data.direction===x?'selected':'')+'" data-lost-direction="'+i+'">'+esc(x)+'</button>'}).join("")+'</div>'+nav(false);
 if(step==="week")host.innerHTML='<div class="hero"><div class="eyebrow">9 · Une semaine à +10 %</div><h2>À quoi ressemblerait une semaine seulement 10 % plus proche de cette direction&nbsp;?</h2><p class="muted">Pas une nouvelle vie. Une différence assez petite pour être testée.</p></div><div class="field"><textarea id="lostWeek" placeholder="Ex. réserver une soirée sans travail, appeler une personne du métier, marcher 20 minutes deux fois…">'+esc(data.week10||"")+'</textarea></div><div class="insight">Quand tu ne sais pas encore où aller, cherche d’abord dans quelle direction faire un pas.</div>'+nav(false);
 if(step==="action")host.innerHTML='<div class="hero"><div class="eyebrow">10 · Prochain pas</div><h2>Quel petit test peux-tu faire cette semaine&nbsp;?</h2><p class="muted">Choisis une action qui t’aide à apprendre quelque chose sur cette direction.</p></div><div class="card soft-green"><label>Mon test</label><input id="lostAction" type="text" placeholder="Ex. Échanger 20 minutes avec quelqu’un qui a changé de métier" value="'+esc(data.action||"")+'"></div><div class="field"><label>Quand ?</label><input id="lostDate" type="date" value="'+esc(data.actionDate||"")+'"></div>'+nav(false);
 if(step==="summary")host.innerHTML='<div class="hero"><div class="eyebrow">Ta direction du moment</div><h2>Tu n’as pas besoin d’un plan complet pour avancer.</h2></div><div class="summary-grid">'+item("Domaine",data.area)+item("Ce qui te brouille",data.context)+item("Ce qui donne de l’énergie",data.givesEnergy)+item("Ce qui t’épuise",data.drains)+item("Ce qui compte",data.matters)+item("À préserver",data.anchors)+item("Ce qui manque",data.missing)+item("Plus de / moins de",(data.more||"—")+" / "+(data.less||"—"))+item("Direction",data.direction)+item("Semaine à +10 %",data.week10)+'</div><div class="card soft-green"><div class="eyebrow">Prochain test</div><h3>'+esc(data.action||"À définir")+'</h3><p>'+(data.actionDate?fmtDate(data.actionDate):"Sans date définie")+'</p></div><div class="insight">Cette direction n’est pas une promesse. Le test sert à recueillir une information : <b>est-ce que cette piste te rapproche réellement de ce qui compte ?</b></div><button class="cta" id="lostFinish">Enregistrer dans Mon parcours</button><div style="height:10px"></div><button class="secondary" id="lostEdit">Modifier une réponse</button>';
 bind(step);updateNext(step);sticky();save();requestAnimationFrame(function(){window.scrollTo(0,0)});
}
function capture(step){function v(id){var e=document.getElementById(id);return e?e.value.trim():""}if(step==="context"){data.context=v("lostContext");data.since=v("lostSince")}if(step==="map"){data.givesEnergy=v("givesEnergy");data.drains=v("drains");data.matters=v("matters");data.canWait=v("canWait")}if(step==="focus")data.focus=v("lostFocus");if(step==="anchors")data.anchors=v("lostAnchors");if(step==="missing")data.missing=v("lostMissing");if(step==="moreLess"){data.more=v("lostMore");data.less=v("lostLess")}if(step==="week")data.week10=v("lostWeek");if(step==="action"){data.action=v("lostAction");data.actionDate=v("lostDate")}}
function valid(step){if(step==="area")return !!data.area;if(step==="context")return !!data.context;if(step==="map")return !!data.givesEnergy&&!!data.drains&&!!data.matters;if(step==="focus")return !!data.focus;if(step==="anchors")return !!data.anchors;if(step==="missing")return !!data.missing;if(step==="moreLess")return !!data.more&&!!data.less;if(step==="direction")return !!data.direction;if(step==="week")return !!data.week10;if(step==="action")return !!data.action;return true}
function updateNext(step){var n=document.getElementById("lostNext");if(!n)return;capture(step);n.disabled=!valid(step)}
function only(sel,b){document.querySelectorAll(sel).forEach(function(x){x.classList.remove("selected")});b.classList.add("selected")}
function bind(step){var back=document.getElementById("lostBack"),next=document.getElementById("lostNext");if(back)back.onclick=function(){capture(step);if(stepIndex>0){stepIndex--;render()}};if(next)next.onclick=function(){capture(step);if(valid(step)){stepIndex++;render()}};document.querySelectorAll("[data-lost-area]").forEach(function(b){b.onclick=function(){data.area=areas[Number(b.dataset.lostArea)];only("[data-lost-area]",b);save();updateNext(step)}});document.querySelectorAll("[data-lost-direction]").forEach(function(b){b.onclick=function(){data.direction=directions[Number(b.dataset.lostDirection)];only("[data-lost-direction]",b);save();updateNext(step)}});document.querySelectorAll("#flow input,#flow textarea").forEach(function(x){x.addEventListener("input",function(){capture(step);save();updateNext(step)});x.addEventListener("change",function(){capture(step);save();updateNext(step)})});var f=document.getElementById("lostFinish");if(f)f.onclick=finish;var e=document.getElementById("lostEdit");if(e)e.onclick=function(){stepIndex=1;render()}}
function finish(){var h=history();h.unshift({id:Date.now(),type:"lost",createdAt:new Date().toISOString(),decision:"Je me sens perdu(e) — "+(data.area||"direction"),priorities:[data.direction||"Direction à explorer"],action:data.action||"",actionDate:data.actionDate||"",learned:"",done:false,area:data.area||"",context:data.context||"",direction:data.direction||"",week10:data.week10||""});localStorage.setItem(HISTORY,JSON.stringify(h));clear();active=false;document.querySelector('[data-tab="journey"]').click()}
document.querySelectorAll("[data-lost-start]").forEach(function(b){b.addEventListener("click",function(){start(true)})});
document.querySelectorAll('[data-start="decision"]').forEach(function(b){b.addEventListener("click",function(){localStorage.removeItem(LOST_STORAGE)},{capture:true})});document.querySelectorAll("[data-confidence-start]").forEach(function(b){b.addEventListener("click",function(){localStorage.removeItem(LOST_STORAGE)},{capture:true})});document.querySelectorAll("[data-pro-start]").forEach(function(b){b.addEventListener("click",function(){localStorage.removeItem(LOST_STORAGE)},{capture:true})});
var resume=document.getElementById("resumeBtn");if(resume)resume.addEventListener("click",function(e){if(noOther()&&localStorage.getItem(LOST_STORAGE)){e.preventDefault();e.stopImmediatePropagation();start(false)}},{capture:true});
var reset=document.getElementById("resetBtn");if(reset)reset.addEventListener("click",function(e){if(active){e.preventDefault();e.stopImmediatePropagation();if(window.confirm("Recommencer ce parcours ? Tes réponses en cours seront effacées.")){clear();start(true)}}},{capture:true});
var erase=document.getElementById("eraseBtn");if(erase)erase.addEventListener("click",function(e){if(active||localStorage.getItem(LOST_STORAGE)){e.preventDefault();e.stopImmediatePropagation();if(window.confirm("Effacer toutes les données locales de Clarity sur cet appareil ?")){localStorage.removeItem(DECISION_STORAGE);localStorage.removeItem(PRO_STORAGE);localStorage.removeItem(CONF_STORAGE);localStorage.removeItem(LOST_STORAGE);localStorage.removeItem(HISTORY);window.location.reload()}}},{capture:true});
document.querySelectorAll("[data-tab]").forEach(function(b){b.addEventListener("click",function(){active=false})});window.addEventListener("resize",sticky);if(read()&&noOther())showResume();
})();