(function(){
"use strict";
var MOT_STORAGE="clarity_v0_motivation_state",HISTORY="clarity_v0_history";
var OTHER=["clarity_v0_state","clarity_v0_confidence_state","clarity_v0_procrastination_state","clarity_v0_lost_state","clarity_v0_rumination_state","clarity_v0_limits_state","clarity_v0_failure_state"];
var active=false,stepIndex=0,data={};
var steps=["intro","goal","scope","gauges","lowest","why","wantMust","benefit","before","progress","permission","direction","branch","action","summary"];
var scopes=["Surtout pour cet objectif","Pour plusieurs choses en ce moment","J’ai l’impression de manquer d’énergie presque partout","Je ne sais pas"];
var reasons=["Parce que j’en ai vraiment envie","Parce que c’est important pour moi","Parce que je pense que je devrais","Parce que d’autres l’attendent de moi","Parce que j’ai déjà beaucoup investi dedans","Je ne sais plus vraiment pourquoi"];
var directions=[
 {id:"restart",label:"Relancer",hint:"L’objectif me convient encore, mais j’ai besoin d’un redémarrage plus simple."},
 {id:"modify",label:"Modifier",hint:"Je veux garder l’intention, mais changer la manière ou l’objectif."},
 {id:"pause",label:"Mettre en pause",hint:"Ce n’est pas le bon moment pour y consacrer de l’énergie."},
 {id:"drop",label:"Laisser partir",hint:"Je ne veux peut-être plus poursuivre cet objectif."}
];
function esc(s){return String(s||"").replace(/[&<>"']/g,function(m){return({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"})[m]});}
function nav(disabled){return '<div class="navrow"><button class="secondary" id="motBack" '+(disabled?'disabled':'')+'>Retour</button><button class="cta" id="motNext">Continuer</button></div>';}
function item(t,v){return '<div class="summary-item"><b>'+esc(t)+'</b><span>'+esc(v||"—")+'</span></div>';}
function fmtDate(iso){if(!iso)return "";return new Date(iso+"T12:00:00").toLocaleDateString("fr-FR",{day:"numeric",month:"long",year:"numeric"});}
function history(){try{return JSON.parse(localStorage.getItem(HISTORY)||"[]")}catch(e){return[]}}
function noOther(){return OTHER.every(function(k){return !localStorage.getItem(k)})}
function clearOthers(){OTHER.forEach(function(k){localStorage.removeItem(k)})}
function read(){try{var raw=localStorage.getItem(MOT_STORAGE);if(!raw)return false;var s=JSON.parse(raw);data=s.data||{};stepIndex=Number.isInteger(s.step)?s.step:0;if(stepIndex<0||stepIndex>=steps.length)stepIndex=0;return true}catch(e){return false}}
function save(){localStorage.setItem(MOT_STORAGE,JSON.stringify({data:data,step:stepIndex}));showResume();}
function clear(){localStorage.removeItem(MOT_STORAGE);data={};stepIndex=0;}
function showResume(){if(!noOther())return;var c=document.getElementById("resumeCard"),t=document.getElementById("resumeText");if(!c||!t)return;c.classList.remove("hidden");t.textContent=data.goal?"Tu regardais ta motivation autour de : « "+data.goal+" »":"Tu as un parcours La Jauge d’énergie en cours.";}
function sticky(){var t=document.querySelector(".topbar");if(t)document.documentElement.style.setProperty("--topbar-h",t.offsetHeight+"px");}
function start(fresh){if(fresh){clearOthers();clear()}else read();document.querySelectorAll(".screen").forEach(function(s){s.classList.remove("active")});document.getElementById("flow").classList.add("active");document.querySelector(".bottom").classList.add("hidden");document.getElementById("resetBtn").classList.remove("hidden");document.querySelectorAll(".tab").forEach(function(t){t.classList.remove("active")});active=true;render();}
function gaugeLabel(k){var labels={physical:"Énergie physique",mental:"Énergie mentale",desire:"Envie",meaning:"Sens",clarity:"Clarté",reward:"Récompense / progrès visible"};return labels[k]||k;}
function lowestGauge(){var keys=["physical","mental","desire","meaning","clarity","reward"],best=null;keys.forEach(function(k){var v=Number((data.gauges||{})[k]||0);if(v>0&&(!best||v<best.value))best={key:k,value:v};});return best;}
function gaugeRow(key,label){var value=Number((data.gauges||{})[key]||0);return '<div class="card"><h3>'+esc(label)+'</h3><div class="chips">'+[1,2,3,4,5].map(function(n){return '<button class="chip '+(value===n?'selected':'')+'" data-mot-gauge="'+key+'" data-value="'+n+'">'+n+'</button>'}).join("")+'</div><p class="muted">1 = très bas · 5 = élevé</p></div>';}
function directionLabel(){var d=directions.find(function(x){return x.id===data.direction});return d?d.label:"—";}
function branchPrompt(){var low=lowestGauge();if(data.direction==="restart")return {title:"Relancer",q:"Quel redémarrage serait assez petit pour recréer du mouvement ?",ph:"Ex. 15 minutes, une seule séance, une première version…"};if(data.direction==="modify")return {title:"Modifier",q:"Qu’est-ce que tu veux changer pour que cet objectif te convienne davantage ?",ph:"Ex. réduire la fréquence, changer la méthode, viser autre chose…"};if(data.direction==="pause")return {title:"Mettre en pause",q:"Que dois-tu décider clairement pour que cette pause libère vraiment de l’énergie ?",ph:"Ex. je mets ce projet en pause jusqu’au 15 septembre, sans culpabiliser entre-temps…"};if(data.direction==="drop")return {title:"Laisser partir",q:"Qu’est-ce que tu veux arrêter de porter — et que veux-tu récupérer en échange ?",ph:"Ex. j’arrête cet objectif pour récupérer du temps et de l’énergie pour…"};if(low&&low.key==="physical")return {title:"Réduire la charge",q:"Que peux-tu alléger avant d’essayer de produire plus d’effort ?",ph:"Un engagement, une durée, une exigence…"};return {title:"Choisir une réponse",q:"Quelle réponse te paraît la plus juste maintenant ?",ph:""};}
function generalEnergyNotice(){return '<div class="notice">Si ce manque d’énergie touche plusieurs domaines depuis un certain temps, Clarity ne va pas le réduire à un simple problème de motivation. Réduire la charge et récupérer peut être plus pertinent. Si cela persiste, s’aggrave ou t’inquiète, en parler à un professionnel de santé peut aussi être utile.</div>';}
function proposedAction(){if(data.direction==="pause")return data.branch||"Définir clairement la durée de ma pause";if(data.direction==="drop")return data.branch||"Retirer cet objectif de ma liste";return data.branch||data.visibleProgress||"";}
function render(){
 var step=steps[stepIndex],host=document.getElementById("flowContent"),flow=document.getElementById("flow");
 flow.classList.toggle("sticky-question",step!=="intro"&&step!=="summary");
 document.getElementById("progress").style.width=Math.round(stepIndex/(steps.length-1)*100)+"%";
 if(step==="intro")host.innerHTML='<div class="hero"><div class="eyebrow">La Jauge d’énergie</div><h2>Le manque de motivation n’a pas toujours la même cause.</h2><p>On va regarder ton énergie, ton envie, le sens, la clarté et le retour que cet objectif te donne — puis choisir s’il faut le relancer, le modifier, le mettre en pause ou le laisser partir.</p></div><div class="card soft-green"><b>Objectif</b><p>Ne pas te forcer à vouloir davantage. Comprendre ce qui manque réellement pour choisir une réponse adaptée.</p></div>'+nav(true);
 if(step==="goal")host.innerHTML='<div class="hero"><div class="eyebrow">1 · L’objectif</div><h2>Pour quoi aimerais-tu retrouver de la motivation&nbsp;?</h2><p class="muted">Choisis une activité ou un objectif précis.</p></div><div class="field"><label>Mon objectif / activité</label><textarea id="motGoal" placeholder="Ex. reprendre le sport, avancer sur mon projet, chercher un nouvel emploi…">'+esc(data.goal||"")+'</textarea></div><div class="field"><label>Depuis quand la motivation a baissé ? <span class="muted">(facultatif)</span></label><input id="motSince" type="text" placeholder="Ex. depuis environ un mois" value="'+esc(data.since||"")+'"></div>'+nav(false);
 if(step==="scope")host.innerHTML='<div class="hero"><div class="eyebrow">2 · L’étendue</div><h2>Ce manque d’élan concerne-t-il surtout cet objectif ou beaucoup de choses&nbsp;?</h2></div><div class="choices">'+scopes.map(function(x){return '<button class="choice '+(data.scope===x?'selected':'')+'" data-mot-scope="'+esc(x)+'">'+esc(x)+'</button>'}).join("")+'</div>'+((data.scope==="Pour plusieurs choses en ce moment"||data.scope==="J’ai l’impression de manquer d’énergie presque partout")?generalEnergyNotice():"")+nav(false);
 if(step==="gauges")host.innerHTML='<div class="hero"><div class="eyebrow">3 · Ta Jauge d’énergie</div><h2>Note chaque dimension pour cet objectif, aujourd’hui.</h2><p class="muted">Ce n’est pas une mesure médicale. C’est une photo subjective pour voir où se trouve la friction.</p></div>'+gaugeRow("physical","Énergie physique")+gaugeRow("mental","Énergie mentale")+gaugeRow("desire","Envie")+gaugeRow("meaning","Sens")+gaugeRow("clarity","Clarté")+gaugeRow("reward","Récompense / progrès visible")+nav(false);
 if(step==="lowest"){var low=lowestGauge();host.innerHTML='<div class="hero"><div class="eyebrow">4 · Le point faible</div><h2>La jauge la plus basse est : '+esc(low?gaugeLabel(low.key):"—")+'.</h2><p class="muted">Qu’est-ce qui explique cette note basse dans ta situation ?</p></div><div class="field"><textarea id="motLowestWhy" placeholder="Ex. je suis épuisé(e) le soir / je ne vois plus pourquoi je fais ça / je ne sais pas quelle est la prochaine étape…">'+esc(data.lowestWhy||"")+'</textarea></div>'+nav(false)}
 if(step==="why")host.innerHTML='<div class="hero"><div class="eyebrow">5 · Pourquoi cet objectif existe</div><h2>Quelle raison ressemble le plus à la tienne aujourd’hui&nbsp;?</h2></div><div class="choices">'+reasons.map(function(x){return '<button class="choice '+(data.reason===x?'selected':'')+'" data-mot-reason="'+esc(x)+'">'+esc(x)+'</button>'}).join("")+'</div>'+nav(false);
 if(step==="wantMust")host.innerHTML='<div class="hero"><div class="eyebrow">6 · “Je veux” ou “Je dois”</div><h2>Si personne ne te jugeait et que tu n’avais rien à prouver, voudrais-tu encore poursuivre cet objectif&nbsp;?</h2></div><div class="choices">'+["Oui","Oui, mais autrement","Je ne sais pas","Probablement pas"].map(function(x){return '<button class="choice '+(data.stillWant===x?'selected':'')+'" data-mot-want="'+esc(x)+'">'+esc(x)+'</button>'}).join("")+'</div>'+nav(false);
 if(step==="benefit")host.innerHTML='<div class="hero"><div class="eyebrow">7 · Ce que tu cherches vraiment</div><h2>Qu’espères-tu obtenir grâce à cet objectif&nbsp;?</h2><p class="muted">Puis demande-toi s’il existe une autre manière d’obtenir une partie de ce bénéfice.</p></div><div class="field"><label>Ce que j’espère obtenir</label><textarea id="motBenefit" placeholder="Ex. me sentir mieux dans mon corps, évoluer, gagner en liberté…">'+esc(data.benefit||"")+'</textarea></div><div class="field"><label>Une autre manière possible <span class="muted">(facultatif)</span></label><textarea id="motAlternative" placeholder="Ex. une activité plus courte, un autre projet, une autre façon d’apprendre…">'+esc(data.alternative||"")+'</textarea></div>'+nav(false);
 if(step==="before")host.innerHTML='<div class="hero"><div class="eyebrow">8 · Quand ça fonctionnait mieux</div><h2>Quand tu avais davantage d’élan, qu’est-ce qui était différent&nbsp;?</h2><p class="muted">Rythme, environnement, personnes, niveau de difficulté, sommeil, nouveauté, résultats visibles…</p></div><div class="field"><textarea id="motBefore" placeholder="Ex. j’avais un rendez-vous fixe, je voyais mes progrès, je faisais ça avec quelqu’un…">'+esc(data.before||"")+'</textarea></div>'+nav(false);
 if(step==="progress")host.innerHTML='<div class="hero"><div class="eyebrow">9 · Rendre le progrès visible</div><h2>Quel signe rapide pourrait te montrer que tu avances&nbsp;?</h2><p class="muted">Une case cochée, un temps passé, une répétition, un résultat observable, une petite récompense.</p></div><div class="field"><label>Mon signe de progrès</label><input id="motProgress" type="text" placeholder="Ex. 2 séances cette semaine / envoyer une candidature / 20 minutes réalisées" value="'+esc(data.visibleProgress||"")+'"></div>'+nav(false);
 if(step==="permission")host.innerHTML='<div class="hero"><div class="eyebrow">10 · Permission de réévaluer</div><h2>Si tu décidais de ne plus poursuivre cet objectif tel quel, qu’est-ce que cela libérerait — et qu’est-ce que tu regretterais&nbsp;?</h2></div><div class="card soft-green"><div class="field"><label>Ce que ça libérerait</label><textarea id="motFree" placeholder="Temps, énergie, argent, pression…">'+esc(data.free||"")+'</textarea></div></div><div class="card cream"><div class="field"><label>Ce que je pourrais regretter</label><textarea id="motRegret" placeholder="Une possibilité, un bénéfice, une identité, une expérience…">'+esc(data.regret||"")+'</textarea></div></div>'+nav(false);
 if(step==="direction")host.innerHTML='<div class="hero"><div class="eyebrow">11 · Choisir la bonne réponse</div><h2>Quelle direction te paraît la plus juste maintenant&nbsp;?</h2><p class="muted">Arrêter ou mettre en pause peut être une décision valide. Clarity ne considère pas “continuer” comme la seule réussite.</p></div><div class="choices">'+directions.map(function(x){return '<button class="choice '+(data.direction===x.id?'selected':'')+'" data-mot-direction="'+x.id+'"><b>'+esc(x.label)+'</b><span class="muted" style="display:block;font-size:13px;margin-top:4px;font-weight:500">'+esc(x.hint)+'</span></button>'}).join("")+'</div>'+nav(false);
 if(step==="branch"){var b=branchPrompt();host.innerHTML='<div class="hero"><div class="eyebrow">12 · '+esc(b.title)+'</div><h2>'+esc(b.q)+'</h2></div><div class="field"><textarea id="motBranch" placeholder="'+esc(b.ph)+'">'+esc(data.branch||"")+'</textarea></div>'+((data.direction==="pause")?'<div class="insight">Une pause claire vaut mieux qu’un objectif officiellement actif mais constamment repoussé.</div>':"")+((data.direction==="drop")?'<div class="insight">Laisser partir un objectif qui ne te correspond plus peut libérer de l’énergie pour quelque chose de plus important.</div>':"")+nav(false)}
 if(step==="action"){var p=proposedAction();host.innerHTML='<div class="hero"><div class="eyebrow">13 · Prochain pas</div><h2>Quelle action rend cette décision réelle&nbsp;?</h2></div><div class="card soft-green"><label>Mon prochain pas</label><input id="motAction" type="text" value="'+esc(data.action||p)+'" placeholder="Ex. Bloquer 15 minutes mardi / retirer cet objectif de ma liste"></div><div class="field"><label>Quand ? <span class="muted">(facultatif)</span></label><input id="motDate" type="date" value="'+esc(data.actionDate||"")+'"></div>'+nav(false)}
 if(step==="summary"){var low2=lowestGauge();host.innerHTML='<div class="hero"><div class="eyebrow">Ta Jauge d’énergie</div><h2>Le but n’était pas de fabriquer de la motivation, mais de comprendre ce qu’elle te signalait.</h2></div><div class="summary-grid">'+item("Objectif",data.goal)+item("Étendue",data.scope)+item("Jauge la plus basse",low2?gaugeLabel(low2.key)+" · "+low2.value+" / 5":"—")+item("Ce qui l’explique",data.lowestWhy)+item("Raison actuelle",data.reason)+item("Est-ce que tu le veux encore ?",data.stillWant)+item("Bénéfice recherché",data.benefit)+item("Quand ça marchait mieux",data.before)+item("Signe de progrès",data.visibleProgress)+item("Direction choisie",directionLabel())+'</div><div class="card soft-green"><div class="eyebrow">Prochain pas</div><h3>'+esc(data.action||"À définir")+'</h3><p>'+(data.actionDate?fmtDate(data.actionDate):"Sans date définie")+'</p></div><div class="insight">Ta décision actuelle est <b>'+esc(directionLabel())+'</b>. Le suivi servira à vérifier si ce choix libère réellement de l’énergie ou demande encore un ajustement.</div><button class="cta" id="motFinish">Enregistrer dans Mon parcours</button><div style="height:10px"></div><button class="secondary" id="motEdit">Modifier une réponse</button>'}
 bind(step);updateNext(step);sticky();save();requestAnimationFrame(function(){window.scrollTo(0,0)});
}
function capture(step){function v(id){var e=document.getElementById(id);return e?e.value.trim():""}if(step==="goal"){data.goal=v("motGoal");data.since=v("motSince")}if(step==="lowest")data.lowestWhy=v("motLowestWhy");if(step==="benefit"){data.benefit=v("motBenefit");data.alternative=v("motAlternative")}if(step==="before")data.before=v("motBefore");if(step==="progress")data.visibleProgress=v("motProgress");if(step==="permission"){data.free=v("motFree");data.regret=v("motRegret")}if(step==="branch")data.branch=v("motBranch");if(step==="action"){data.action=v("motAction");data.actionDate=v("motDate")}}
function valid(step){if(step==="goal")return !!data.goal;if(step==="scope")return !!data.scope;if(step==="gauges"){var g=data.gauges||{};return ["physical","mental","desire","meaning","clarity","reward"].every(function(k){return !!Number(g[k])})}if(step==="lowest")return !!data.lowestWhy;if(step==="why")return !!data.reason;if(step==="wantMust")return !!data.stillWant;if(step==="benefit")return !!data.benefit;if(step==="before")return !!data.before;if(step==="progress")return !!data.visibleProgress;if(step==="permission")return !!data.free&&!!data.regret;if(step==="direction")return !!data.direction;if(step==="branch")return !!data.branch;if(step==="action")return !!data.action;return true}
function updateNext(step){var n=document.getElementById("motNext");if(!n)return;capture(step);n.disabled=!valid(step)}
function only(sel,b){document.querySelectorAll(sel).forEach(function(x){x.classList.remove("selected")});b.classList.add("selected")}
function bind(step){var back=document.getElementById("motBack"),next=document.getElementById("motNext");if(back)back.onclick=function(){capture(step);if(stepIndex>0){stepIndex--;render()}};if(next)next.onclick=function(){capture(step);if(valid(step)){stepIndex++;render()}};
 document.querySelectorAll("[data-mot-scope]").forEach(function(b){b.onclick=function(){data.scope=b.dataset.motScope;render()}});
 document.querySelectorAll("[data-mot-gauge]").forEach(function(b){b.onclick=function(){data.gauges=data.gauges||{};data.gauges[b.dataset.motGauge]=Number(b.dataset.value);render()}});
 document.querySelectorAll("[data-mot-reason]").forEach(function(b){b.onclick=function(){data.reason=b.dataset.motReason;only("[data-mot-reason]",b);save();updateNext(step)}});
 document.querySelectorAll("[data-mot-want]").forEach(function(b){b.onclick=function(){data.stillWant=b.dataset.motWant;only("[data-mot-want]",b);save();updateNext(step)}});
 document.querySelectorAll("[data-mot-direction]").forEach(function(b){b.onclick=function(){data.direction=b.dataset.motDirection;data.branch="";only("[data-mot-direction]",b);save();updateNext(step)}});
 document.querySelectorAll("#flow input,#flow textarea").forEach(function(x){x.addEventListener("input",function(){capture(step);save();updateNext(step)});x.addEventListener("change",function(){capture(step);save();updateNext(step)})});
 var finish=document.getElementById("motFinish");if(finish)finish.onclick=finishSession;var edit=document.getElementById("motEdit");if(edit)edit.onclick=function(){stepIndex=1;render()};
}
function finishSession(){var h=history(),low=lowestGauge();h.unshift({id:Date.now(),type:"motivation",createdAt:new Date().toISOString(),decision:data.goal||"Motivation",priorities:["Direction : "+directionLabel(),low?"Point bas : "+gaugeLabel(low.key):""].filter(Boolean),action:data.action||"",actionDate:data.actionDate||"",learned:"",done:false,motivationDirection:data.direction||"",lowestGauge:low?low.key:"",benefit:data.benefit||""});localStorage.setItem(HISTORY,JSON.stringify(h));clear();active=false;document.querySelector('[data-tab="journey"]').click()}
document.querySelectorAll("[data-motivation-start]").forEach(function(b){b.addEventListener("click",function(){start(true)})});
OTHER.forEach(function(){ });
var resume=document.getElementById("resumeBtn");if(resume)resume.addEventListener("click",function(e){if(noOther()&&localStorage.getItem(MOT_STORAGE)){e.preventDefault();e.stopImmediatePropagation();start(false)}},{capture:true});
var reset=document.getElementById("resetBtn");if(reset)reset.addEventListener("click",function(e){if(active){e.preventDefault();e.stopImmediatePropagation();if(window.confirm("Recommencer ce parcours ? Tes réponses en cours seront effacées.")){clear();start(true)}}},{capture:true});
document.querySelectorAll("[data-tab]").forEach(function(b){b.addEventListener("click",function(){active=false})});window.addEventListener("resize",sticky);if(read()&&noOther())showResume();
})();