(function(){
"use strict";
var RUM_STORAGE="clarity_v0_rumination_state",DECISION_STORAGE="clarity_v0_state",PRO_STORAGE="clarity_v0_procrastination_state",CONF_STORAGE="clarity_v0_confidence_state",LOST_STORAGE="clarity_v0_lost_state",HISTORY="clarity_v0_history";
var active=false,stepIndex=0,data={};
var steps=["intro","loop","seeking","control","facts","story","alternatives","useful","cost","info","redirect","parking","action","summary"];
var seeking=["Comprendre ce qui s’est passé","Être certain(e) de ce qui va arriver","Savoir ce que quelqu’un pense","Être sûr(e) de prendre la bonne décision","Me rassurer","Passer en revue toutes les possibilités"];
var redirects=["Agir sur ce qui dépend de moi","Demander une information","Attendre un fait nouveau","Accepter une part d’incertitude","Mettre cette question de côté pour maintenant"];
var revisit=["Plus tard aujourd’hui","Demain","Cette semaine","Seulement s’il y a une information nouvelle"];
function esc(s){return String(s||"").replace(/[&<>"']/g,function(m){return({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"})[m]});}
function nav(disabled){return '<div class="navrow"><button class="secondary" id="rumBack" '+(disabled?'disabled':'')+'>Retour</button><button class="cta" id="rumNext">Continuer</button></div>';}
function item(t,v){return '<div class="summary-item"><b>'+esc(t)+'</b><span>'+esc(v||"—")+'</span></div>';}
function fmtDate(iso){if(!iso)return "";return new Date(iso+"T12:00:00").toLocaleDateString("fr-FR",{day:"numeric",month:"long",year:"numeric"});}
function history(){try{return JSON.parse(localStorage.getItem(HISTORY)||"[]")}catch(e){return[]}}
function otherStores(){return [DECISION_STORAGE,PRO_STORAGE,CONF_STORAGE,LOST_STORAGE]}
function noOther(){return otherStores().every(function(k){return !localStorage.getItem(k)})}
function clearOthers(){otherStores().forEach(function(k){localStorage.removeItem(k)})}
function read(){try{var raw=localStorage.getItem(RUM_STORAGE);if(!raw)return false;var s=JSON.parse(raw);data=s.data||{};stepIndex=Number.isInteger(s.step)?s.step:0;if(stepIndex<0||stepIndex>=steps.length)stepIndex=0;return true}catch(e){return false}}
function save(){localStorage.setItem(RUM_STORAGE,JSON.stringify({data:data,step:stepIndex}));showResume();}
function clear(){localStorage.removeItem(RUM_STORAGE);data={};stepIndex=0;}
function showResume(){if(!noOther())return;var c=document.getElementById("resumeCard"),t=document.getElementById("resumeText");if(!c||!t)return;c.classList.remove("hidden");t.textContent=data.loop?"Tu travaillais sur : « "+data.loop+" »":"Tu as un parcours Le Cercle de contrôle en cours.";}
function sticky(){var t=document.querySelector(".topbar");if(t)document.documentElement.style.setProperty("--topbar-h",t.offsetHeight+"px");}
function start(fresh){if(fresh){clearOthers();clear()}else read();document.querySelectorAll(".screen").forEach(function(s){s.classList.remove("active")});document.getElementById("flow").classList.add("active");document.querySelector(".bottom").classList.add("hidden");document.getElementById("resetBtn").classList.remove("hidden");document.querySelectorAll(".tab").forEach(function(t){t.classList.remove("active")});active=true;render();}
function usefulInsight(){if(data.usefulness==="Oui, clairement")return "Ta réflexion produit encore de l’information. L’objectif est de définir précisément laquelle, puis d’arrêter quand tu l’as obtenue.";if(data.usefulness==="Un peu")return "Il reste peut-être une question utile, mais une partie de la réflexion semble déjà se répéter.";if(data.usefulness==="Non, je répète surtout les mêmes choses")return "Quand aucune information nouvelle n’apparaît, continuer à penser n’est plus forcément la même chose que résoudre.";return "Le test le plus simple : demande-toi ce que tu sais maintenant que tu ne savais pas il y a dix minutes.";}
function proposedAction(){var map={"Agir sur ce qui dépend de moi":"Faire une action qui dépend uniquement de moi","Demander une information":"Poser une question concrète à la bonne personne","Attendre un fait nouveau":"Ne pas rouvrir la question avant un fait nouveau","Accepter une part d’incertitude":"Faire mon prochain pas sans chercher une certitude totale","Mettre cette question de côté pour maintenant":"Mettre cette question de côté jusqu’au moment prévu"};return map[data.redirect]||"";}
function render(){
 var step=steps[stepIndex],host=document.getElementById("flowContent"),flow=document.getElementById("flow");
 flow.classList.toggle("sticky-question",step!=="intro"&&step!=="summary");
 document.getElementById("progress").style.width=Math.round(stepIndex/(steps.length-1)*100)+"%";
 if(step==="intro")host.innerHTML='<div class="hero"><div class="eyebrow">Le Cercle de contrôle</div><h2>Penser plus n’apporte pas toujours plus de clarté.</h2><p>On va séparer les faits, les interprétations et ce qui dépend réellement de toi, puis chercher la prochaine information ou action utile.</p></div><div class="card soft-green"><b>Objectif</b><p>Passer d’une boucle mentale à une question vérifiable, une action concrète ou une décision consciente de laisser une part d’incertitude.</p></div>'+nav(true);
 if(step==="loop")host.innerHTML='<div class="hero"><div class="eyebrow">1 · La boucle</div><h2>Qu’est-ce qui tourne en boucle dans ta tête&nbsp;?</h2><p class="muted">Formule la question ou la situation qui revient le plus souvent.</p></div><div class="field"><label>Ce qui revient</label><textarea id="rumLoop" placeholder="Ex. Pourquoi il ne m’a pas répondu ? Est-ce que j’ai fait quelque chose de mal ?">'+esc(data.loop||"")+'</textarea></div><div class="field"><label>Quand la boucle revient-elle le plus ? <span class="muted">(facultatif)</span></label><input id="rumWhen" type="text" placeholder="Ex. le soir, après avoir regardé mon téléphone…" value="'+esc(data.when||"")+'"></div>'+nav(false);
 if(step==="seeking")host.innerHTML='<div class="hero"><div class="eyebrow">2 · Ce que tu cherches</div><h2>Quand tu y repenses, qu’essaies-tu surtout d’obtenir&nbsp;?</h2></div><div class="choices">'+seeking.map(function(x,i){return '<button class="choice '+(data.seeking===x?'selected':'')+'" data-rum-seeking="'+i+'">'+esc(x)+'</button>'}).join("")+'</div>'+nav(false);
 if(step==="control")host.innerHTML='<div class="hero"><div class="eyebrow">3 · Le Cercle de contrôle</div><h2>Place les éléments de la situation dans les trois zones.</h2><p class="muted">Le but n’est pas de tout contrôler, mais de voir où ton énergie peut réellement produire quelque chose.</p></div><div class="card soft-green"><div class="field"><label>Ça dépend de moi</label><textarea id="rumControl" placeholder="Mes mots, mes choix, ce que je demande, ce que je fais…">'+esc(data.control||"")+'</textarea></div></div><div class="card cream"><div class="field"><label>Je peux influencer, pas contrôler</label><textarea id="rumInfluence" placeholder="Une discussion, une demande, une proposition…">'+esc(data.influence||"")+'</textarea></div></div><div class="card coral"><div class="field"><label>Ça ne dépend pas de moi</label><textarea id="rumOutside" placeholder="La réaction de quelqu’un, le passé, une décision extérieure…">'+esc(data.outside||"")+'</textarea></div></div>'+nav(false);
 if(step==="facts")host.innerHTML='<div class="hero"><div class="eyebrow">4 · Les faits</div><h2>Qu’est-ce que tu sais réellement, sans interprétation&nbsp;?</h2><p class="muted">Uniquement ce qui pourrait être observé, entendu, lu ou vérifié.</p></div><div class="field"><textarea id="rumFacts" placeholder="Ex. J’ai envoyé un message mardi. Il a été lu. Je n’ai pas reçu de réponse.">'+esc(data.facts||"")+'</textarea></div>'+nav(false);
 if(step==="story"){var c=Number(data.confidence||0);host.innerHTML='<div class="hero"><div class="eyebrow">5 · L’histoire que ton esprit complète</div><h2>Quelle interprétation ajoutes-tu aux faits&nbsp;?</h2></div><div class="card coral"><div class="field"><label>Ce que j’en conclus ou imagine</label><textarea id="rumStory" placeholder="Ex. Il m’en veut, j’ai fait quelque chose de mal…">'+esc(data.story||"")+'</textarea></div></div><h3>À quel point es-tu certain(e) que cette interprétation est vraie ?</h3><div class="chips">'+[1,2,3,4,5].map(function(n){return '<button class="chip '+(c===n?'selected':'')+'" data-rum-confidence="'+n+'">'+n+'</button>'}).join("")+'</div><p class="muted">1 = une possibilité parmi d’autres · 5 = j’ai des éléments très solides.</p>'+nav(false)}
 if(step==="alternatives")host.innerHTML='<div class="hero"><div class="eyebrow">6 · Autres explications possibles</div><h2>Quelle autre explication est plausible avec les mêmes faits&nbsp;?</h2><p class="muted">Pas une version positive forcée. Seulement une autre hypothèse compatible avec ce que tu sais.</p></div><div class="field"><textarea id="rumAlternative" placeholder="Ex. Il est occupé, il ne sait pas quoi répondre, il veut prendre du temps…">'+esc(data.alternative||"")+'</textarea></div>'+nav(false);
 if(step==="useful")host.innerHTML='<div class="hero"><div class="eyebrow">7 · Réflexion utile ou circulaire</div><h2>Est-ce que réfléchir encore t’apporte une information réellement nouvelle&nbsp;?</h2></div><div class="choices">'+["Oui, clairement","Un peu","Non, je répète surtout les mêmes choses","Je ne sais pas"].map(function(x){return '<button class="choice '+(data.usefulness===x?'selected':'')+'" data-rum-useful="'+esc(x)+'">'+esc(x)+'</button>'}).join("")+'</div>'+(data.usefulness?'<div class="insight">'+usefulInsight()+'</div>':'')+((data.usefulness==="Oui, clairement"||data.usefulness==="Un peu")?'<div class="field"><label>Quelle information nouvelle cherches-tu encore ?</label><textarea id="rumNewInfo" placeholder="Une question précise, pas une certitude générale…">'+esc(data.newInfo||"")+'</textarea></div>':'')+nav(false);
 if(step==="cost")host.innerHTML='<div class="hero"><div class="eyebrow">8 · Le coût de la boucle</div><h2>Qu’est-ce que cette réflexion répétée te coûte aujourd’hui&nbsp;?</h2><p class="muted">Temps, énergie, sommeil, concentration, capacité à profiter d’autre chose…</p></div><div class="field"><textarea id="rumCost" placeholder="Ex. Je vérifie mon téléphone toutes les dix minutes et je n’arrive pas à travailler…">'+esc(data.cost||"")+'</textarea></div>'+nav(false);
 if(step==="info")host.innerHTML='<div class="hero"><div class="eyebrow">9 · Revenir à la réalité</div><h2>Existe-t-il une information réelle que tu peux obtenir&nbsp;?</h2></div><div class="choices">'+["Je peux vérifier quelque chose","Je peux poser une question","Je peux observer ce qui se passe","Aucune information disponible pour l’instant"].map(function(x){return '<button class="choice '+(data.infoMode===x?'selected':'')+'" data-rum-info="'+esc(x)+'">'+esc(x)+'</button>'}).join("")+'</div>'+(data.infoMode&&data.infoMode!=="Aucune information disponible pour l’instant"?'<div class="field"><label>L’information concrète à obtenir</label><textarea id="rumInfoText" placeholder="Ex. lui demander directement s’il souhaite qu’on en reparle…">'+esc(data.infoText||"")+'</textarea></div>':'')+(data.infoMode==="Aucune information disponible pour l’instant"?'<div class="insight">S’il n’y a aucune nouvelle information accessible maintenant, continuer à simuler des scénarios ne peut pas combler ce manque.</div>':'')+nav(false);
 if(step==="redirect")host.innerHTML='<div class="hero"><div class="eyebrow">10 · Où mettre ton énergie</div><h2>Quelle réponse est la plus utile maintenant&nbsp;?</h2></div><div class="choices">'+redirects.map(function(x,i){return '<button class="choice '+(data.redirect===x?'selected':'')+'" data-rum-redirect="'+i+'">'+esc(x)+'</button>'}).join("")+'</div>'+nav(false);
 if(step==="parking")host.innerHTML='<div class="hero"><div class="eyebrow">11 · Sortir de la boucle</div><h2>Quand la pensée revient, quelle phrase peut te rappeler où tu en es&nbsp;?</h2><p class="muted">Une phrase factuelle, pas une formule magique.</p></div><div class="field"><label>Ma phrase de rappel</label><textarea id="rumParking" placeholder="Ex. Je n’ai pas d’information nouvelle pour l’instant. J’ai déjà choisi mon prochain pas.">'+esc(data.parking||"")+'</textarea></div><h3>Quand veux-tu réexaminer cette question ?</h3><div class="choices">'+revisit.map(function(x,i){return '<button class="choice '+(data.revisit===x?'selected':'')+'" data-rum-revisit="'+i+'">'+esc(x)+'</button>'}).join("")+'</div>'+nav(false);
 if(step==="action"){var p=proposedAction();host.innerHTML='<div class="hero"><div class="eyebrow">12 · Prochain pas</div><h2>Que vas-tu faire à la place de continuer la boucle&nbsp;?</h2><p class="muted">Une action, une question, une attente consciente ou une limite mentale claire.</p></div><div class="card soft-green"><label>Mon prochain pas</label><input id="rumAction" type="text" placeholder="Ex. Envoyer une question claire, puis ne plus vérifier avant demain" value="'+esc(data.action||p)+'"></div><div class="field"><label>Quand ? <span class="muted">(facultatif)</span></label><input id="rumDate" type="date" value="'+esc(data.actionDate||"")+'"></div>'+nav(false)}
 if(step==="summary")host.innerHTML='<div class="hero"><div class="eyebrow">Ton Cercle de contrôle</div><h2>Tu n’as pas besoin de résoudre ce que tu ne peux pas encore savoir.</h2></div><div class="summary-grid">'+item("Ce qui tourne en boucle",data.loop)+item("Ce que tu cherches",data.seeking)+item("Les faits",data.facts)+item("Ton interprétation",data.story)+item("Certitude sur cette interprétation",data.confidence?data.confidence+" / 5":"—")+item("Une autre explication plausible",data.alternative)+item("Ça dépend de toi",data.control)+item("Ça ne dépend pas de toi",data.outside)+item("La boucle te coûte",data.cost)+item("Information accessible",data.infoMode==="Aucune information disponible pour l’instant"?data.infoMode:data.infoText)+item("Direction choisie",data.redirect)+item("Phrase de rappel",data.parking)+'</div><div class="card soft-green"><div class="eyebrow">Prochain pas</div><h3>'+esc(data.action||"À définir")+'</h3><p>'+(data.actionDate?fmtDate(data.actionDate):"Sans date définie")+'</p></div><div class="insight">Réfléchir reste utile tant que cela produit une information, une décision ou une action nouvelle. Sinon, le prochain progrès peut être de <b>cesser temporairement de chercher une réponse qui n’est pas disponible</b>.</div><button class="cta" id="rumFinish">Enregistrer dans Mon parcours</button><div style="height:10px"></div><button class="secondary" id="rumEdit">Modifier une réponse</button>';
 bind(step);updateNext(step);sticky();save();requestAnimationFrame(function(){window.scrollTo(0,0)});
}
function capture(step){function v(id){var e=document.getElementById(id);return e?e.value.trim():""}if(step==="loop"){data.loop=v("rumLoop");data.when=v("rumWhen")}if(step==="control"){data.control=v("rumControl");data.influence=v("rumInfluence");data.outside=v("rumOutside")}if(step==="facts")data.facts=v("rumFacts");if(step==="story")data.story=v("rumStory");if(step==="alternatives")data.alternative=v("rumAlternative");if(step==="useful")data.newInfo=v("rumNewInfo");if(step==="cost")data.cost=v("rumCost");if(step==="info")data.infoText=v("rumInfoText");if(step==="parking")data.parking=v("rumParking");if(step==="action"){data.action=v("rumAction");data.actionDate=v("rumDate")}}
function valid(step){if(step==="loop")return !!data.loop;if(step==="seeking")return !!data.seeking;if(step==="control")return !!data.control&&!!data.outside;if(step==="facts")return !!data.facts;if(step==="story")return !!data.story&&!!data.confidence;if(step==="alternatives")return !!data.alternative;if(step==="useful")return !!data.usefulness&&((data.usefulness==="Oui, clairement"||data.usefulness==="Un peu")?!!data.newInfo:true);if(step==="cost")return !!data.cost;if(step==="info")return !!data.infoMode&&(data.infoMode==="Aucune information disponible pour l’instant"||!!data.infoText);if(step==="redirect")return !!data.redirect;if(step==="parking")return !!data.parking&&!!data.revisit;if(step==="action")return !!data.action;return true}
function updateNext(step){var n=document.getElementById("rumNext");if(!n)return;capture(step);n.disabled=!valid(step)}
function only(sel,b){document.querySelectorAll(sel).forEach(function(x){x.classList.remove("selected")});b.classList.add("selected")}
function bind(step){var back=document.getElementById("rumBack"),next=document.getElementById("rumNext");if(back)back.onclick=function(){capture(step);if(stepIndex>0){stepIndex--;render()}};if(next)next.onclick=function(){capture(step);if(valid(step)){stepIndex++;render()}};
 document.querySelectorAll("[data-rum-seeking]").forEach(function(b){b.onclick=function(){data.seeking=seeking[Number(b.dataset.rumSeeking)];only("[data-rum-seeking]",b);save();updateNext(step)}});
 document.querySelectorAll("[data-rum-confidence]").forEach(function(b){b.onclick=function(){data.confidence=Number(b.dataset.rumConfidence);render()}});
 document.querySelectorAll("[data-rum-useful]").forEach(function(b){b.onclick=function(){data.usefulness=b.dataset.rumUseful;if(data.usefulness!=="Oui, clairement"&&data.usefulness!=="Un peu")data.newInfo="";render()}});
 document.querySelectorAll("[data-rum-info]").forEach(function(b){b.onclick=function(){data.infoMode=b.dataset.rumInfo;if(data.infoMode==="Aucune information disponible pour l’instant")data.infoText="";render()}});
 document.querySelectorAll("[data-rum-redirect]").forEach(function(b){b.onclick=function(){data.redirect=redirects[Number(b.dataset.rumRedirect)];render()}});
 document.querySelectorAll("[data-rum-revisit]").forEach(function(b){b.onclick=function(){data.revisit=revisit[Number(b.dataset.rumRevisit)];only("[data-rum-revisit]",b);save();updateNext(step)}});
 document.querySelectorAll("#flow input,#flow textarea").forEach(function(e){e.addEventListener("input",function(){capture(step);save();updateNext(step)});e.addEventListener("change",function(){capture(step);save();updateNext(step)})});
 var finish=document.getElementById("rumFinish");if(finish)finish.onclick=finishSession;var edit=document.getElementById("rumEdit");if(edit)edit.onclick=function(){stepIndex=1;render()};
}
function finishSession(){var h=history();h.unshift({id:Date.now(),type:"rumination",createdAt:new Date().toISOString(),decision:data.loop||"Boucle mentale",priorities:["Cercle de contrôle",data.redirect||""].filter(Boolean),action:data.action||"",actionDate:data.actionDate||"",learned:"",done:false,facts:data.facts||"",story:data.story||"",control:data.control||"",outside:data.outside||"",parking:data.parking||""});localStorage.setItem(HISTORY,JSON.stringify(h));clear();active=false;document.querySelector('[data-tab="journey"]').click()}
document.querySelectorAll("[data-rumination-start]").forEach(function(b){b.addEventListener("click",function(){start(true)})});
[ '[data-start="decision"]','[data-confidence-start]','[data-pro-start]','[data-lost-start]' ].forEach(function(sel){document.querySelectorAll(sel).forEach(function(b){b.addEventListener("click",function(){localStorage.removeItem(RUM_STORAGE)},{capture:true})})});
var resume=document.getElementById("resumeBtn");if(resume)resume.addEventListener("click",function(e){if(noOther()&&localStorage.getItem(RUM_STORAGE)){e.preventDefault();e.stopImmediatePropagation();start(false)}},{capture:true});
var reset=document.getElementById("resetBtn");if(reset)reset.addEventListener("click",function(e){if(active){e.preventDefault();e.stopImmediatePropagation();if(window.confirm("Recommencer ce parcours ? Tes réponses en cours seront effacées.")){clear();start(true)}}},{capture:true});
document.querySelectorAll("[data-tab]").forEach(function(b){b.addEventListener("click",function(){active=false})});window.addEventListener("resize",sticky);if(read()&&noOther())showResume();
})();